#!/usr/bin/env bash
# update_formula.sh — Tự động tạo/cập nhật Formula từ bottle JSON files
# Chạy sau khi build.sh hoàn thành, trước khi commit vào repo

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BOTTLES_DIR="${BOTTLES_DIR:-$REPO_ROOT/bottles}"
FORMULA_DIR="$REPO_ROOT/Formula"
RELEASE_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/stable"

mkdir -p "$FORMULA_DIR"

echo "=== Formula Updater ==="
echo "Reading bottles from: $BOTTLES_DIR"
echo ""

# Tìm tất cả bottle JSON files
JSON_FILES=("$BOTTLES_DIR"/*.bottle.json)

if [ ${#JSON_FILES[@]} -eq 0 ] || [ ! -f "${JSON_FILES[0]}" ]; then
  echo "No bottle JSON files found in $BOTTLES_DIR"
  exit 1
fi

for json_file in "${JSON_FILES[@]}"; do
  echo "Processing: $(basename "$json_file")"

  # Parse JSON để lấy thông tin cần thiết
  pkg_name=$(jq -r 'keys[0]' "$json_file")
  version=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.pkg_version' "$json_file")
  bottle_file=$(jq -r --arg pkg "$pkg_name" '.[$pkg].bottle.tags | to_entries[0].value.filename' "$json_file")
  sha256=$(jq -r --arg pkg "$pkg_name" '.[$pkg].bottle.tags | to_entries[0].value.sha256' "$json_file")
  homepage=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.homepage' "$json_file")
  desc=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.desc' "$json_file")

  # Normalize tên formula (python@3.13 → python@3.13.rb)
  formula_name=$(echo "$pkg_name" | tr '@' '@')
  formula_file="$FORMULA_DIR/${formula_name}.rb"

  echo "  Package : $pkg_name"
  echo "  Version : $version"
  echo "  Bottle  : $bottle_file"
  echo "  SHA256  : $sha256"

  # Lấy dependencies từ JSON
  deps=$(jq -r --arg pkg "$pkg_name" '
    .[$pkg].formula.dependencies // [] | 
    map("  depends_on \"" + . + "\"") | 
    join("\n")
  ' "$json_file")

  # Tạo formula Ruby
  cat > "$formula_file" << RUBY
# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
class $(echo "$pkg_name" | sed 's/@/At/g; s/\b./\u&/g; s/-//g') < Formula
  desc "$desc"
  homepage "$homepage"
  version "$version"
  # No source URL needed — install via bottle only
  url "https://github.com/${GITHUB_REPOSITORY}/releases/download/stable/${bottle_file}"
  sha256 "$sha256"

${deps}

  bottle do
    root_url "$RELEASE_URL"
    sha256 monterey: "$sha256"
    sha256 ventura:  "$sha256"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/${pkg_name}", "--version"
  end
end
RUBY

  echo "  ✅ Formula written: $(basename "$formula_file")"
  echo ""
done

echo "All formulas updated in: $FORMULA_DIR"
