# Auto-generated by update_formula.sh
class UadaUurl < Formula
  desc "WHATWG-compliant and fast URL parser written in modern C++"
  homepage "https://github.com/ada-url/ada"
  version "3.4.4"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ada-url--3.4.4.sequoia.bottle.tar.gz"
  sha256 "e873bf3af53bd3fb037336dc1044f5da19e6d581b7e6ca00bcf25708bc48c5ac"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "e873bf3af53bd3fb037336dc1044f5da19e6d581b7e6ca00bcf25708bc48c5ac"
    sha256 ventura: "e873bf3af53bd3fb037336dc1044f5da19e6d581b7e6ca00bcf25708bc48c5ac"
    sha256 monterey: "e873bf3af53bd3fb037336dc1044f5da19e6d581b7e6ca00bcf25708bc48c5ac"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
