# Auto-generated by update_formula.sh
class Uargon2 < Formula
  desc "Password hashing library and CLI utility"
  homepage "https://github.com/P-H-C/phc-winner-argon2"
  version "20190702_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/argon2--20190702_1.sequoia.bottle.tar.gz"
  sha256 "8ed6a3e027daef7d5d857839ae8513f4d7a36671ffd4cfffa16296fc14f00934"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "8ed6a3e027daef7d5d857839ae8513f4d7a36671ffd4cfffa16296fc14f00934"
    sha256 ventura: "8ed6a3e027daef7d5d857839ae8513f4d7a36671ffd4cfffa16296fc14f00934"
    sha256 monterey: "8ed6a3e027daef7d5d857839ae8513f4d7a36671ffd4cfffa16296fc14f00934"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
