# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-31 02:36:01 UTC
class aria2 < Formula
  desc "Download with resuming and segmented downloading"
  homepage "https://aria2.github.io/"
  version "1.37.0_1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/aria2-1.37.0_1.sequoia.bottle.2.tar.gz"
  sha256 "71269a28ef6d297ebbb92f42730fa1796e2361349ad057a08438ba9db0413b95"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "71269a28ef6d297ebbb92f42730fa1796e2361349ad057a08438ba9db0413b95"
    sha256 ventura:  "71269a28ef6d297ebbb92f42730fa1796e2361349ad057a08438ba9db0413b95"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/aria2", "--version"
  end
end
