# Auto-generated by update_formula.sh
class Automake < Formula
  desc "Tool for generating GNU Standards-compliant Makefiles"
  homepage "https://www.gnu.org/software/automake/"
  version "1.18.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/automake--1.18.1.sequoia.bottle.tar.gz"
  sha256 "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
    sha256 ventura: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
    sha256 monterey: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
