# Auto-generated by update_formula.sh
class Uautoconf < Formula
  desc "Automatic configure script builder"
  homepage "https://www.gnu.org/software/autoconf/"
  version "2.73"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/autoconf--2.73.sequoia.bottle.tar.gz"
  sha256 "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
    sha256 ventura: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
    sha256 monterey: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
