# Auto-generated by update_formula.sh
class Autoconf < Formula
  desc "Automatic configure script builder"
  homepage "https://www.gnu.org/software/autoconf/"
  version "2.73"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/autoconf--2.73.sequoia.bottle.tar.gz"
  sha256 "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
    sha256 ventura: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
    sha256 monterey: "9d7a8c7582d4036ed5187087d49328b8aa9690b536869cc23e80653b46beb8ee"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
