# Auto-generated by update_formula.sh
class Uautomake < Formula
  desc "Tool for generating GNU Standards-compliant Makefiles"
  homepage "https://www.gnu.org/software/automake/"
  version "1.18.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/automake--1.18.1.sequoia.bottle.tar.gz"
  sha256 "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
    sha256 ventura: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
    sha256 monterey: "1ecd2b8d3433325176ece3ebe4b783b55f26ac776f0cd812b790e300b4e756e3"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
