# Auto-generated by update_formula.sh
class Ubrotli < Formula
  desc "Generic-purpose lossless compression algorithm by Google"
  homepage "https://github.com/google/brotli"
  version "1.2.0"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/brotli--1.2.0.sequoia.bottle.tar.gz"
  sha256 "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
    sha256 ventura: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
    sha256 monterey: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
