# Auto-generated by update_formula.sh
class Brotli < Formula
  desc "Generic-purpose lossless compression algorithm by Google"
  homepage "https://github.com/google/brotli"
  version "1.2.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/brotli--1.2.0.sequoia.bottle.tar.gz"
  sha256 "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
    sha256 ventura: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
    sha256 monterey: "13420d3ff3bcc1e04acbbd7f0d96d42f4d1cfa856f7cbc3870f0e53e982963cb"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
