# Auto-generated by update_formula.sh
class UcUares < Formula
  desc "Asynchronous DNS library"
  homepage "https://c-ares.org/"
  version "1.34.6"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/c-ares--1.34.6.sequoia.bottle.tar.gz"
  sha256 "593ca89b007ac5bfaf2d0e7d75c7991d2e1ffa0018e6bb89f46a010597c07af0"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "593ca89b007ac5bfaf2d0e7d75c7991d2e1ffa0018e6bb89f46a010597c07af0"
    sha256 ventura: "593ca89b007ac5bfaf2d0e7d75c7991d2e1ffa0018e6bb89f46a010597c07af0"
    sha256 monterey: "593ca89b007ac5bfaf2d0e7d75c7991d2e1ffa0018e6bb89f46a010597c07af0"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
