# Auto-generated by update_formula.sh
class CaCertificates < Formula
  desc "Mozilla CA certificate store"
  homepage "https://curl.se/docs/caextract.html"
  version "2026-03-19"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ca-certificates--2026-03-19.sequoia.bottle.tar.gz"
  sha256 "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
    sha256 ventura: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
    sha256 monterey: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
