# Auto-generated by update_formula.sh
class UcaUcertificates < Formula
  desc "Mozilla CA certificate store"
  homepage "https://curl.se/docs/caextract.html"
  version "2026-03-19"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ca-certificates--2026-03-19.sequoia.bottle.tar.gz"
  sha256 "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
    sha256 ventura: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
    sha256 monterey: "a2597e50b0c21477142e9f2b66c25508d287b1bd9bb4d4211203d1433cc049e8"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
