# Auto-generated by update_formula.sh
class Cmake < Formula
  desc "Cross-platform make"
  homepage "https://www.cmake.org/"
  version "4.3.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/cmake--4.3.1.sequoia.bottle.tar.gz"
  sha256 "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
    sha256 ventura: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
    sha256 monterey: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
