# Auto-generated by update_formula.sh
class Ucmake < Formula
  desc "Cross-platform make"
  homepage "https://www.cmake.org/"
  version "4.3.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/cmake--4.3.1.sequoia.bottle.tar.gz"
  sha256 "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
    sha256 ventura: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
    sha256 monterey: "89f7a45ad093cf6e568b5da94a04da1235ff60c0b2df6c73ea2df87699b50927"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
