# Auto-generated by update_formula.sh
class Cxxopts < Formula
  desc "Lightweight C++ command-line option parser"
  homepage "https://github.com/jarro2783/cxxopts"
  version "3.3.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/cxxopts--3.3.1.sequoia.bottle.tar.gz"
  sha256 "1a01714f0b5b4f65a04f411b1951e204855dc01b52236ecfad9a920b71122bfc"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "1a01714f0b5b4f65a04f411b1951e204855dc01b52236ecfad9a920b71122bfc"
    sha256 ventura: "1a01714f0b5b4f65a04f411b1951e204855dc01b52236ecfad9a920b71122bfc"
    sha256 monterey: "1a01714f0b5b4f65a04f411b1951e204855dc01b52236ecfad9a920b71122bfc"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
