# Auto-generated by update_formula.sh
class Dav1d < Formula
  desc "AV1 decoder targeted to be small and fast"
  homepage "https://code.videolan.org/videolan/dav1d"
  version "1.5.3"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/dav1d--1.5.3.sequoia.bottle.1.tar.gz"
  sha256 "94f8e5d24ca8bfd03c22f005df39a721171cb246e1de78ebad83648a5337eea9"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
