# Auto-generated by update_formula.sh
class Dav1d < Formula
  desc "AV1 decoder targeted to be small and fast"
  homepage "https://code.videolan.org/videolan/dav1d"
  version "1.5.3"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/dav1d--1.5.3.sequoia.bottle.tar.gz"
  sha256 "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
    sha256 ventura: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
    sha256 monterey: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
