# Auto-generated by update_formula.sh
class Udav1d < Formula
  desc "AV1 decoder targeted to be small and fast"
  homepage "https://code.videolan.org/videolan/dav1d"
  version "1.5.3"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/dav1d--1.5.3.sequoia.bottle.tar.gz"
  sha256 "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
    sha256 ventura: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
    sha256 monterey: "781f7fbbdfd798cfbad423df60ec3882ae513b7403678370795df44e76f83d36"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
