# Auto-generated by update_formula.sh
class Udeno < Formula
  desc "Secure runtime for JavaScript and TypeScript"
  homepage "https://deno.com/"
  version "2.7.11"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/deno--2.7.11.sequoia.bottle.tar.gz"
  sha256 "f8f650e6ec622910e3bcdecbb11ef0840b6ac7557bd76dcb7be56a436c23deaa"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "f8f650e6ec622910e3bcdecbb11ef0840b6ac7557bd76dcb7be56a436c23deaa"
    sha256 ventura: "f8f650e6ec622910e3bcdecbb11ef0840b6ac7557bd76dcb7be56a436c23deaa"
    sha256 monterey: "f8f650e6ec622910e3bcdecbb11ef0840b6ac7557bd76dcb7be56a436c23deaa"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
