# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-29 09:38:27 UTC
class ffmpeg < Formula
  desc "Play, record, convert, and stream select audio and video codecs"
  homepage "https://ffmpeg.org/"
  version "8.1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ffmpeg-8.1.sequoia.bottle.2.tar.gz"
  sha256 "54957602afd36712de7e5162e98e4afd0ae1248bb43e3301ac69172ec056e004"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "54957602afd36712de7e5162e98e4afd0ae1248bb43e3301ac69172ec056e004"
    sha256 ventura:  "54957602afd36712de7e5162e98e4afd0ae1248bb43e3301ac69172ec056e004"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/ffmpeg", "--version"
  end
end
