# Auto-generated by update_formula.sh
class Ffmpeg < Formula
  desc "Play, record, convert, and stream select audio and video codecs"
  homepage "https://ffmpeg.org/"
  version "8.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ffmpeg--8.1.sequoia.bottle.tar.gz"
  sha256 "50efa73b226f9866445002e457114bd1bd2723b6b899ec5bfda14819ae8fe4cd"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "50efa73b226f9866445002e457114bd1bd2723b6b899ec5bfda14819ae8fe4cd"
    sha256 ventura: "50efa73b226f9866445002e457114bd1bd2723b6b899ec5bfda14819ae8fe4cd"
    sha256 monterey: "50efa73b226f9866445002e457114bd1bd2723b6b899ec5bfda14819ae8fe4cd"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
