# Auto-generated by update_formula.sh
class Ufmt < Formula
  desc "Open-source formatting library for C++"
  homepage "https://fmt.dev/"
  version "12.1.0"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/fmt--12.1.0.sequoia.bottle.tar.gz"
  sha256 "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
    sha256 ventura: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
    sha256 monterey: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
