# Auto-generated by update_formula.sh
class Fmt < Formula
  desc "Open-source formatting library for C++"
  homepage "https://fmt.dev/"
  version "12.1.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/fmt--12.1.0.sequoia.bottle.tar.gz"
  sha256 "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
    sha256 ventura: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
    sha256 monterey: "c80da1069be8f9986def3bba61eead19665731eb52a8ed5d23f0e4cb975f3c91"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
