# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-28 16:40:28 UTC
class fzf < Formula
  desc "Command-line fuzzy finder written in Go"
  homepage "https://github.com/junegunn/fzf"
  version "0.70.0"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/fzf-0.70.0.sequoia.bottle.1.tar.gz"
  sha256 "bb872cc5ba75eaf0987ec99ed8089dd811d4e412844d2aa594f49d958f29a6fa"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "bb872cc5ba75eaf0987ec99ed8089dd811d4e412844d2aa594f49d958f29a6fa"
    sha256 ventura:  "bb872cc5ba75eaf0987ec99ed8089dd811d4e412844d2aa594f49d958f29a6fa"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/fzf", "--version"
  end
end
