# Auto-generated by update_formula.sh
class Gettext < Formula
  desc "GNU internationalization (i18n) and localization (l10n) library"
  homepage "https://www.gnu.org/software/gettext/"
  version "1.0"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/gettext--1.0.sequoia.bottle.1.tar.gz"
  sha256 "6191e60ee0f3a10210c89dd0ba5f3a9a4aa32338a0e53e239efbd0adfb1f5d50"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
