# Auto-generated by update_formula.sh
class Gettext < Formula
  desc "GNU internationalization (i18n) and localization (l10n) library"
  homepage "https://www.gnu.org/software/gettext/"
  version "1.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/gettext--1.0.sequoia.bottle.tar.gz"
  sha256 "2ab881f49d5977d6be1a110e4bfc18cf79112202a0c5bbf292073698c10afb41"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "2ab881f49d5977d6be1a110e4bfc18cf79112202a0c5bbf292073698c10afb41"
    sha256 ventura: "2ab881f49d5977d6be1a110e4bfc18cf79112202a0c5bbf292073698c10afb41"
    sha256 monterey: "2ab881f49d5977d6be1a110e4bfc18cf79112202a0c5bbf292073698c10afb41"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
