# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-31 02:36:02 UTC
class go < Formula
  desc "Open source programming language to build simple/reliable/efficient software"
  homepage "https://go.dev/"
  version "1.26.1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/go-1.26.1.sequoia.bottle.1.tar.gz"
  sha256 "818738f363616d051ff13707a3384116dabb77e1d7c5ffc76ac34d0d54e9d28e"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "818738f363616d051ff13707a3384116dabb77e1d7c5ffc76ac34d0d54e9d28e"
    sha256 ventura:  "818738f363616d051ff13707a3384116dabb77e1d7c5ffc76ac34d0d54e9d28e"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/go", "--version"
  end
end
