# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-28 16:40:28 UTC
class go < Formula
  desc "Open source programming language to build simple/reliable/efficient software"
  homepage "https://go.dev/"
  version "1.26.1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/go-1.26.1.sequoia.bottle.1.tar.gz"
  sha256 "f3f6d5380abb106e7c9c3c1c3cd2e626da57a243da352b1c98bd6d859c419bbb"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "f3f6d5380abb106e7c9c3c1c3cd2e626da57a243da352b1c98bd6d859c419bbb"
    sha256 ventura:  "f3f6d5380abb106e7c9c3c1c3cd2e626da57a243da352b1c98bd6d859c419bbb"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/go", "--version"
  end
end
