# Auto-generated by update_formula.sh
class HdrhistogramC < Formula
  desc "C port of the HdrHistogram"
  homepage "https://github.com/HdrHistogram/HdrHistogram_c"
  version "0.11.9"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/hdrhistogram_c--0.11.9.sequoia.bottle.tar.gz"
  sha256 "c2afc128fa84a7609fdef3580ada2b4d356a77433a4a5cf68f805342b130fd7e"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "c2afc128fa84a7609fdef3580ada2b4d356a77433a4a5cf68f805342b130fd7e"
    sha256 ventura: "c2afc128fa84a7609fdef3580ada2b4d356a77433a4a5cf68f805342b130fd7e"
    sha256 monterey: "c2afc128fa84a7609fdef3580ada2b4d356a77433a4a5cf68f805342b130fd7e"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
