# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-29 09:38:28 UTC
class hugo < Formula
  desc "Configurable static site generator"
  homepage "https://gohugo.io/"
  version "0.159.1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/hugo-0.159.1.sequoia.bottle.1.tar.gz"
  sha256 "7cc297e2fd576173022b29ac8e227287a4fce9256f0373ca420e040079bd3e2b"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "7cc297e2fd576173022b29ac8e227287a4fce9256f0373ca420e040079bd3e2b"
    sha256 ventura:  "7cc297e2fd576173022b29ac8e227287a4fce9256f0373ca420e040079bd3e2b"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/hugo", "--version"
  end
end
