# Auto-generated by update_formula.sh
class Hugo < Formula
  desc "Configurable static site generator"
  homepage "https://gohugo.io/"
  version "0.160.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/hugo--0.160.0.sequoia.bottle.tar.gz"
  sha256 "8c65cbee2339d1c5f9f78cd48a69801151aca02cad091966be1abf9f1fe886f7"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "8c65cbee2339d1c5f9f78cd48a69801151aca02cad091966be1abf9f1fe886f7"
    sha256 ventura: "8c65cbee2339d1c5f9f78cd48a69801151aca02cad091966be1abf9f1fe886f7"
    sha256 monterey: "8c65cbee2339d1c5f9f78cd48a69801151aca02cad091966be1abf9f1fe886f7"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
