# Auto-generated by update_formula.sh
class UjpegUturbo < Formula
  desc "JPEG image codec that aids compression and decompression"
  homepage "https://www.libjpeg-turbo.org/"
  version "3.1.4.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/jpeg-turbo--3.1.4.1.sequoia.bottle.tar.gz"
  sha256 "bd96154781f2c5ef27912a787fa1379bc8b2ba679732d994384e56bcfd0a4c0d"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "bd96154781f2c5ef27912a787fa1379bc8b2ba679732d994384e56bcfd0a4c0d"
    sha256 ventura: "bd96154781f2c5ef27912a787fa1379bc8b2ba679732d994384e56bcfd0a4c0d"
    sha256 monterey: "bd96154781f2c5ef27912a787fa1379bc8b2ba679732d994384e56bcfd0a4c0d"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
