# Auto-generated by update_formula.sh
class Ujq < Formula
  desc "Lightweight and flexible command-line JSON processor"
  homepage "https://jqlang.github.io/jq/"
  version "1.8.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/jq--1.8.1.sequoia.bottle.tar.gz"
  sha256 "8c0d001a47456d715b759ed224b334e9f67d4a12cc43db849ffb00954dfaab26"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "8c0d001a47456d715b759ed224b334e9f67d4a12cc43db849ffb00954dfaab26"
    sha256 ventura: "8c0d001a47456d715b759ed224b334e9f67d4a12cc43db849ffb00954dfaab26"
    sha256 monterey: "8c0d001a47456d715b759ed224b334e9f67d4a12cc43db849ffb00954dfaab26"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
