# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-31 02:36:02 UTC
class jq < Formula
  desc "Lightweight and flexible command-line JSON processor"
  homepage "https://jqlang.github.io/jq/"
  version "1.8.1"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/jq-1.8.1.sequoia.bottle.1.tar.gz"
  sha256 "860a0b023752624d6bfd1f9bb10d235099081724657c80e175bb1a2352eed6a9"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "860a0b023752624d6bfd1f9bb10d235099081724657c80e175bb1a2352eed6a9"
    sha256 ventura:  "860a0b023752624d6bfd1f9bb10d235099081724657c80e175bb1a2352eed6a9"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/jq", "--version"
  end
end
