# Auto-generated by update_formula.sh
class Ulibevent < Formula
  desc "Asynchronous event library"
  homepage "https://libevent.org/"
  version "2.1.12_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libevent--2.1.12_1.sequoia.bottle.tar.gz"
  sha256 "9fb3d2d861ebf57cdc707952c64b63f4e151316d56de26bdd1aa8410f5779637"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "9fb3d2d861ebf57cdc707952c64b63f4e151316d56de26bdd1aa8410f5779637"
    sha256 ventura: "9fb3d2d861ebf57cdc707952c64b63f4e151316d56de26bdd1aa8410f5779637"
    sha256 monterey: "9fb3d2d861ebf57cdc707952c64b63f4e151316d56de26bdd1aa8410f5779637"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
