# Auto-generated by update_formula.sh
class Ulibgit2 < Formula
  desc "C library of Git core methods that is re-entrant and linkable"
  homepage "https://libgit2.org/"
  version "1.9.2_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libgit2--1.9.2_1.sequoia.bottle.tar.gz"
  sha256 "8e3a4b0251e7dfa8227a7c6e4d629aa0cbc0dca0d9a27942c80736dc61da4cf2"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "8e3a4b0251e7dfa8227a7c6e4d629aa0cbc0dca0d9a27942c80736dc61da4cf2"
    sha256 ventura: "8e3a4b0251e7dfa8227a7c6e4d629aa0cbc0dca0d9a27942c80736dc61da4cf2"
    sha256 monterey: "8e3a4b0251e7dfa8227a7c6e4d629aa0cbc0dca0d9a27942c80736dc61da4cf2"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
