# Auto-generated by update_formula.sh
class Libgit2 < Formula
  desc "C library of Git core methods that is re-entrant and linkable"
  homepage "https://libgit2.org/"
  version "1.9.2_1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libgit2--1.9.2_1.sequoia.bottle.tar.gz"
  sha256 "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
    sha256 ventura: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
    sha256 monterey: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
