# Auto-generated by update_formula.sh
class Ulibgit2 < Formula
  desc "C library of Git core methods that is re-entrant and linkable"
  homepage "https://libgit2.org/"
  version "1.9.2_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libgit2--1.9.2_1.sequoia.bottle.tar.gz"
  sha256 "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
    sha256 ventura: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
    sha256 monterey: "a71d682036b7fe9542572dcc1fdd45ddaf3e089aaba4e14a4e05347a164f4d89"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
