# Auto-generated by update_formula.sh
class Ulibidn2 < Formula
  desc "International domain name library (IDNA2008, Punycode and TR46)"
  homepage "https://www.gnu.org/software/libidn/#libidn2"
  version "2.3.8"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libidn2--2.3.8.sequoia.bottle.tar.gz"
  sha256 "d59a537d58b065e617db0eeceee3cc908445e0441be4f7fcd5742615903c1da3"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "d59a537d58b065e617db0eeceee3cc908445e0441be4f7fcd5742615903c1da3"
    sha256 ventura: "d59a537d58b065e617db0eeceee3cc908445e0441be4f7fcd5742615903c1da3"
    sha256 monterey: "d59a537d58b065e617db0eeceee3cc908445e0441be4f7fcd5742615903c1da3"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
