# Auto-generated by update_formula.sh
class Libngtcp2 < Formula
  desc "IETF QUIC protocol implementation"
  homepage "https://nghttp2.org/ngtcp2/"
  version "1.22.0"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libngtcp2--1.22.0.sequoia.bottle.1.tar.gz"
  sha256 "60e97b86984fd764afce1f0e407cbc7fe8f1eb8192b728f3586460aafd5cb8c5"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
