# Auto-generated by update_formula.sh
class Libnghttp3 < Formula
  desc "HTTP/3 library written in C"
  homepage "https://nghttp2.org/nghttp3/"
  version "1.15.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libnghttp3--1.15.0.sequoia.bottle.tar.gz"
  sha256 "55484fbfa3256656a64d813558c3d5e0582cfabc423a5a2d042a4d300b8c532f"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "55484fbfa3256656a64d813558c3d5e0582cfabc423a5a2d042a4d300b8c532f"
    sha256 ventura: "55484fbfa3256656a64d813558c3d5e0582cfabc423a5a2d042a4d300b8c532f"
    sha256 monterey: "55484fbfa3256656a64d813558c3d5e0582cfabc423a5a2d042a4d300b8c532f"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
