# Auto-generated by update_formula.sh
class Libnghttp2 < Formula
  desc "HTTP/2 C Library"
  homepage "https://nghttp2.org/"
  version "1.68.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libnghttp2--1.68.1.sequoia.bottle.tar.gz"
  sha256 "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
    sha256 ventura: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
    sha256 monterey: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
