# Auto-generated by update_formula.sh
class Ulibnghttp2 < Formula
  desc "HTTP/2 C Library"
  homepage "https://nghttp2.org/"
  version "1.68.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libnghttp2--1.68.1.sequoia.bottle.tar.gz"
  sha256 "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
    sha256 ventura: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
    sha256 monterey: "9beb2cb6a8551f2cc3eadc3804353a308d17ebf8b295d8b712cd34788e0620de"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
