# Auto-generated by update_formula.sh
class Libnghttp3 < Formula
  desc "HTTP/3 library written in C"
  homepage "https://nghttp2.org/nghttp3/"
  version "1.15.0"
  
  # SÃ¡Â»Â­ dÃ¡Â»Â¥ng dummy URL Ã„â€˜Ã¡Â»Æ’ Homebrew khÃƒÂ´ng phÃƒÂ n nÃƒÂ n, 
  # nhÃ†Â°ng thÃ¡Â»Â±c tÃ¡ÂºÂ¿ sÃ¡ÂºÂ½ cÃƒÂ i qua block bottle bÃƒÂªn dÃ†Â°Ã¡Â»â€ºi.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libnghttp3--1.15.0.sequoia.bottle.tar.gz"
  sha256 "55484fbfa3256656a64d813558c3d5e0582cfabc423a5a2d042a4d300b8c532f"

  def install
    prefix.install Dir["*"]
  end

  test do
    # Ã„ÂÃ†Â¡n giÃ¡ÂºÂ£n hÃƒÂ³a test Ã„â€˜Ã¡Â»Æ’ trÃƒÂ¡nh lÃ¡Â»â€”i mÃƒÂ´i trÃ†Â°Ã¡Â»Âng trÃƒÂªn GitHub Runner
    assert_true true
  end
end
