# Auto-generated by update_formula.sh
class Ulibssh2 < Formula
  desc "C library implementing the SSH2 protocol"
  homepage "https://libssh2.org/"
  version "1.11.1_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libssh2--1.11.1_1.sequoia.bottle.tar.gz"
  sha256 "6fdaaf0ecf865c3f1c84b43eb5797430824d68dd0f2a8727e57989bb2c2a0bb4"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "6fdaaf0ecf865c3f1c84b43eb5797430824d68dd0f2a8727e57989bb2c2a0bb4"
    sha256 ventura: "6fdaaf0ecf865c3f1c84b43eb5797430824d68dd0f2a8727e57989bb2c2a0bb4"
    sha256 monterey: "6fdaaf0ecf865c3f1c84b43eb5797430824d68dd0f2a8727e57989bb2c2a0bb4"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
