# Auto-generated by update_formula.sh
class Libtool < Formula
  desc "Generic library support script"
  homepage "https://www.gnu.org/software/libtool/"
  version "2.5.4"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libtool--2.5.4.sequoia.bottle.tar.gz"
  sha256 "b4ea765b45f5a80f3de5c351afe2e8019d653b80d570c10996daa2c6d8e8781a"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "b4ea765b45f5a80f3de5c351afe2e8019d653b80d570c10996daa2c6d8e8781a"
    sha256 ventura: "b4ea765b45f5a80f3de5c351afe2e8019d653b80d570c10996daa2c6d8e8781a"
    sha256 monterey: "b4ea765b45f5a80f3de5c351afe2e8019d653b80d570c10996daa2c6d8e8781a"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
