# Auto-generated by update_formula.sh
class Ulibtiff < Formula
  desc "TIFF library and utilities"
  homepage "https://libtiff.gitlab.io/libtiff/"
  version "4.7.1_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libtiff--4.7.1_1.sequoia.bottle.tar.gz"
  sha256 "c64d263798a99556b466237da8e32cbe861240b38c28bb07ee3530f2d7a8f931"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "c64d263798a99556b466237da8e32cbe861240b38c28bb07ee3530f2d7a8f931"
    sha256 ventura: "c64d263798a99556b466237da8e32cbe861240b38c28bb07ee3530f2d7a8f931"
    sha256 monterey: "c64d263798a99556b466237da8e32cbe861240b38c28bb07ee3530f2d7a8f931"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
