# Auto-generated by update_formula.sh
class Libuv < Formula
  desc "Multi-platform support library with a focus on asynchronous I/O"
  homepage "https://libuv.org/"
  version "1.52.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libuv--1.52.1.sequoia.bottle.tar.gz"
  sha256 "c3daf681f4aa75f6d133a6d242326fa480e0a32d7361e4f08e3e1421cb0d9811"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "c3daf681f4aa75f6d133a6d242326fa480e0a32d7361e4f08e3e1421cb0d9811"
    sha256 ventura: "c3daf681f4aa75f6d133a6d242326fa480e0a32d7361e4f08e3e1421cb0d9811"
    sha256 monterey: "c3daf681f4aa75f6d133a6d242326fa480e0a32d7361e4f08e3e1421cb0d9811"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
