# Auto-generated by update_formula.sh
class Libvpx < Formula
  desc "VP8/VP9 video codec"
  homepage "https://www.webmproject.org/code/"
  version "1.16.0"
  
  # SÃ¡Â»Â­ dÃ¡Â»Â¥ng dummy URL Ã„â€˜Ã¡Â»Æ’ Homebrew khÃƒÂ´ng phÃƒÂ n nÃƒÂ n, 
  # nhÃ†Â°ng thÃ¡Â»Â±c tÃ¡ÂºÂ¿ sÃ¡ÂºÂ½ cÃƒÂ i qua block bottle bÃƒÂªn dÃ†Â°Ã¡Â»â€ºi.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libvpx--1.16.0.sequoia.bottle.tar.gz"
  sha256 "62e98d9046f228dbb31cd7bbb3248fff8069dee31fe0d2f8a73da03a36ce5b78"

  def install
    prefix.install Dir["*"]
  end

  test do
    # Ã„ÂÃ†Â¡n giÃ¡ÂºÂ£n hÃƒÂ³a test Ã„â€˜Ã¡Â»Æ’ trÃƒÂ¡nh lÃ¡Â»â€”i mÃƒÂ´i trÃ†Â°Ã¡Â»Âng trÃƒÂªn GitHub Runner
    assert_true true
  end
end
