# Auto-generated by update_formula.sh
class Libvpx < Formula
  desc "VP8/VP9 video codec"
  homepage "https://www.webmproject.org/code/"
  version "1.16.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/libvpx--1.16.0.sequoia.bottle.tar.gz"
  sha256 "62e98d9046f228dbb31cd7bbb3248fff8069dee31fe0d2f8a73da03a36ce5b78"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "62e98d9046f228dbb31cd7bbb3248fff8069dee31fe0d2f8a73da03a36ce5b78"
    sha256 ventura: "62e98d9046f228dbb31cd7bbb3248fff8069dee31fe0d2f8a73da03a36ce5b78"
    sha256 monterey: "62e98d9046f228dbb31cd7bbb3248fff8069dee31fe0d2f8a73da03a36ce5b78"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
