# Auto-generated by update_formula.sh
class Ulld < Formula
  desc "LLVM Project Linker"
  homepage "https://lld.llvm.org/"
  version "22.1.2"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/lld--22.1.2.sequoia.bottle.tar.gz"
  sha256 "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
    sha256 ventura: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
    sha256 monterey: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
