# Auto-generated by update_formula.sh
class Lld < Formula
  desc "LLVM Project Linker"
  homepage "https://lld.llvm.org/"
  version "22.1.2"
  
  # SÃ¡Â»Â­ dÃ¡Â»Â¥ng dummy URL Ã„â€˜Ã¡Â»Æ’ Homebrew khÃƒÂ´ng phÃƒÂ n nÃƒÂ n, 
  # nhÃ†Â°ng thÃ¡Â»Â±c tÃ¡ÂºÂ¿ sÃ¡ÂºÂ½ cÃƒÂ i qua block bottle bÃƒÂªn dÃ†Â°Ã¡Â»â€ºi.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/lld--22.1.2.sequoia.bottle.tar.gz"
  sha256 "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"

  def install
    prefix.install Dir["*"]
  end

  test do
    # Ã„ÂÃ†Â¡n giÃ¡ÂºÂ£n hÃƒÂ³a test Ã„â€˜Ã¡Â»Æ’ trÃƒÂ¡nh lÃ¡Â»â€”i mÃƒÂ´i trÃ†Â°Ã¡Â»Âng trÃƒÂªn GitHub Runner
    assert_true true
  end
end
