# Auto-generated by update_formula.sh
class Lld < Formula
  desc "LLVM Project Linker"
  homepage "https://lld.llvm.org/"
  version "22.1.2"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/lld--22.1.2.sequoia.bottle.tar.gz"
  sha256 "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
    sha256 ventura: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
    sha256 monterey: "f7075a06b25eda36e7a2dcf8c8d61284a8b8338c478b4bb5a66144eb0c473b48"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
