# Auto-generated by update_formula.sh
class Llhttp < Formula
  desc "Port of http_parser to llparse"
  homepage "https://llhttp.org/"
  version "9.3.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/llhttp--9.3.1.sequoia.bottle.tar.gz"
  sha256 "0ca29f8398dafc5e2636864079e1afcf1fe69acf556a83af9e9aaf68b6e2eb42"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "0ca29f8398dafc5e2636864079e1afcf1fe69acf556a83af9e9aaf68b6e2eb42"
    sha256 ventura: "0ca29f8398dafc5e2636864079e1afcf1fe69acf556a83af9e9aaf68b6e2eb42"
    sha256 monterey: "0ca29f8398dafc5e2636864079e1afcf1fe69acf556a83af9e9aaf68b6e2eb42"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
