# Auto-generated by update_formula.sh
class Ullvm < Formula
  desc "Next-gen compiler infrastructure"
  homepage "https://llvm.org/"
  version "22.1.2"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/llvm--22.1.2.sequoia.bottle.tar.gz"
  sha256 "e95b502027c5c5334984b932f5ca0c55ccfd26bb3f69b62f64bfebc33e8fff8f"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "e95b502027c5c5334984b932f5ca0c55ccfd26bb3f69b62f64bfebc33e8fff8f"
    sha256 ventura: "e95b502027c5c5334984b932f5ca0c55ccfd26bb3f69b62f64bfebc33e8fff8f"
    sha256 monterey: "e95b502027c5c5334984b932f5ca0c55ccfd26bb3f69b62f64bfebc33e8fff8f"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
