# Auto-generated by update_formula.sh
class UllvmAt21 < Formula
  desc "Next-gen compiler infrastructure"
  homepage "https://llvm.org/"
  version "21.1.8"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/llvm@21--21.1.8.sequoia.bottle.tar.gz"
  sha256 "72bb37d7acdd328ed9a3305988a9ae7655a2ec709d4e2a516394425858042368"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "72bb37d7acdd328ed9a3305988a9ae7655a2ec709d4e2a516394425858042368"
    sha256 ventura: "72bb37d7acdd328ed9a3305988a9ae7655a2ec709d4e2a516394425858042368"
    sha256 monterey: "72bb37d7acdd328ed9a3305988a9ae7655a2ec709d4e2a516394425858042368"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
