# Auto-generated by update_formula.sh
class Lz4 < Formula
  desc "Extremely Fast Compression algorithm"
  homepage "https://lz4.github.io/lz4/"
  version "1.10.0"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/lz4--1.10.0.sequoia.bottle.tar.gz"
  sha256 "2ae3f190a162f1a40bd147da286147661c367f449e427954f932f20bf5a87ffc"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "2ae3f190a162f1a40bd147da286147661c367f449e427954f932f20bf5a87ffc"
    sha256 ventura: "2ae3f190a162f1a40bd147da286147661c367f449e427954f932f20bf5a87ffc"
    sha256 monterey: "2ae3f190a162f1a40bd147da286147661c367f449e427954f932f20bf5a87ffc"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
