# Auto-generated by update_formula.sh
class Um4 < Formula
  desc "Macro processing language"
  homepage "https://www.gnu.org/software/m4/"
  version "1.4.21"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/m4--1.4.21.sequoia.bottle.tar.gz"
  sha256 "cc5e6a704025db6cebff2264626d57af3a76c8172190f8a629a4c0e0ae388f6c"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "cc5e6a704025db6cebff2264626d57af3a76c8172190f8a629a4c0e0ae388f6c"
    sha256 ventura: "cc5e6a704025db6cebff2264626d57af3a76c8172190f8a629a4c0e0ae388f6c"
    sha256 monterey: "cc5e6a704025db6cebff2264626d57af3a76c8172190f8a629a4c0e0ae388f6c"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
