# Auto-generated by update_formula.sh
class Meson < Formula
  desc "Fast and user friendly build system"
  homepage "https://mesonbuild.com/"
  version "1.10.2"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/meson--1.10.2.sequoia.bottle.tar.gz"
  sha256 "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
    sha256 ventura: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
    sha256 monterey: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
