# Auto-generated by update_formula.sh
class Umeson < Formula
  desc "Fast and user friendly build system"
  homepage "https://mesonbuild.com/"
  version "1.10.2"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/meson--1.10.2.sequoia.bottle.tar.gz"
  sha256 "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
    sha256 ventura: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
    sha256 monterey: "3ee0b2cae841c7764e41b0439b787504d2e59f83cf87cfe2928d08a658fb3d59"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
