# Auto-generated by update_formula.sh
class Mpdecimal < Formula
  desc "Library for decimal floating point arithmetic"
  homepage "https://www.bytereef.org/mpdecimal/"
  version "4.0.1"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/mpdecimal--4.0.1.sequoia.bottle.1.tar.gz"
  sha256 "5662840562b07d26735ae1e901861711ad66d9f5b9a4e6668c4cdf6e9db27b5d"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
