# Auto-generated by update_formula.sh
class Mpdecimal < Formula
  desc "Library for decimal floating point arithmetic"
  homepage "https://www.bytereef.org/mpdecimal/"
  version "4.0.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/mpdecimal--4.0.1.sequoia.bottle.tar.gz"
  sha256 "6c1d85fb16877faeeb712340bfd513fd291b697aacfd5c50aed194e6f8b8e85c"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "6c1d85fb16877faeeb712340bfd513fd291b697aacfd5c50aed194e6f8b8e85c"
    sha256 ventura: "6c1d85fb16877faeeb712340bfd513fd291b697aacfd5c50aed194e6f8b8e85c"
    sha256 monterey: "6c1d85fb16877faeeb712340bfd513fd291b697aacfd5c50aed194e6f8b8e85c"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
