# Auto-generated by update_formula.sh
class Unasm < Formula
  desc "Netwide Assembler (NASM) is an 80x86 assembler"
  homepage "https://www.nasm.us/"
  version "3.01"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/nasm--3.01.sequoia.bottle.tar.gz"
  sha256 "64dbba6913fe79532e422c68d411fdba29f72d61a8f05fc9f30281fa20a945f3"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "64dbba6913fe79532e422c68d411fdba29f72d61a8f05fc9f30281fa20a945f3"
    sha256 ventura: "64dbba6913fe79532e422c68d411fdba29f72d61a8f05fc9f30281fa20a945f3"
    sha256 monterey: "64dbba6913fe79532e422c68d411fdba29f72d61a8f05fc9f30281fa20a945f3"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
