# Auto-generated by update_formula.sh
class Ncurses < Formula
  desc "Text-based UI library"
  homepage "https://invisible-island.net/ncurses/announce.html"
  version "6.6"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/ncurses--6.6.sequoia.bottle.tar.gz"
  sha256 "670d66e0427c704677b8278dcb81a1d1557658f666c8a4010087de20ca7bc72a"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "670d66e0427c704677b8278dcb81a1d1557658f666c8a4010087de20ca7bc72a"
    sha256 ventura: "670d66e0427c704677b8278dcb81a1d1557658f666c8a4010087de20ca7bc72a"
    sha256 monterey: "670d66e0427c704677b8278dcb81a1d1557658f666c8a4010087de20ca7bc72a"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
