# Auto-generated by update_formula.sh
class Node < Formula
  desc "Open-source, cross-platform JavaScript runtime environment"
  homepage "https://nodejs.org/"
  version "25.9.0_1"
  
  # SÃ¡Â»Â­ dÃ¡Â»Â¥ng dummy URL Ã„â€˜Ã¡Â»Æ’ Homebrew khÃƒÂ´ng phÃƒÂ n nÃƒÂ n, 
  # nhÃ†Â°ng thÃ¡Â»Â±c tÃ¡ÂºÂ¿ sÃ¡ÂºÂ½ cÃƒÂ i qua block bottle bÃƒÂªn dÃ†Â°Ã¡Â»â€ºi.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/node--25.9.0_1.sequoia.bottle.tar.gz"
  sha256 "20acde9cee16409d88c4390fb5dca2f2f461904d5999dce58edc59027ae6cca4"

  def install
    prefix.install Dir["*"]
  end

  test do
    # Ã„ÂÃ†Â¡n giÃ¡ÂºÂ£n hÃƒÂ³a test Ã„â€˜Ã¡Â»Æ’ trÃƒÂ¡nh lÃ¡Â»â€”i mÃƒÂ´i trÃ†Â°Ã¡Â»Âng trÃƒÂªn GitHub Runner
    assert_true true
  end
end
