# Auto-generated by update_formula.sh
class Unode < Formula
  desc "Open-source, cross-platform JavaScript runtime environment"
  homepage "https://nodejs.org/"
  version "25.9.0_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/node--25.9.0_1.sequoia.bottle.tar.gz"
  sha256 "20acde9cee16409d88c4390fb5dca2f2f461904d5999dce58edc59027ae6cca4"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "20acde9cee16409d88c4390fb5dca2f2f461904d5999dce58edc59027ae6cca4"
    sha256 ventura: "20acde9cee16409d88c4390fb5dca2f2f461904d5999dce58edc59027ae6cca4"
    sha256 monterey: "20acde9cee16409d88c4390fb5dca2f2f461904d5999dce58edc59027ae6cca4"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
