# Auto-generated by update_formula.sh
class Oniguruma < Formula
  desc "Regular expressions library"
  homepage "https://github.com/kkos/oniguruma/"
  version "6.9.10"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/oniguruma--6.9.10.sequoia.bottle.tar.gz"
  sha256 "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
    sha256 ventura: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
    sha256 monterey: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
