# Auto-generated by update_formula.sh
class Uoniguruma < Formula
  desc "Regular expressions library"
  homepage "https://github.com/kkos/oniguruma/"
  version "6.9.10"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/oniguruma--6.9.10.sequoia.bottle.tar.gz"
  sha256 "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
    sha256 ventura: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
    sha256 monterey: "20c7b317df100302d02f00a3114722473812c009fa8f52c96e8f167508992d2d"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
