# Auto-generated by update_formula.sh
class UopensslAt3 < Formula
  desc "Cryptography and SSL/TLS Toolkit"
  homepage "https://openssl-library.org"
  version "3.6.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/openssl@3--3.6.1.sequoia.bottle.tar.gz"
  sha256 "be802ef8795951cf92a94d6e9efba5825dd3da705449701f2a5111dcf49224b6"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "be802ef8795951cf92a94d6e9efba5825dd3da705449701f2a5111dcf49224b6"
    sha256 ventura: "be802ef8795951cf92a94d6e9efba5825dd3da705449701f2a5111dcf49224b6"
    sha256 monterey: "be802ef8795951cf92a94d6e9efba5825dd3da705449701f2a5111dcf49224b6"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
