# Auto-generated by update_formula.sh
class Uopus < Formula
  desc "Audio codec"
  homepage "https://www.opus-codec.org/"
  version "1.6.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/opus--1.6.1.sequoia.bottle.tar.gz"
  sha256 "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
    sha256 ventura: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
    sha256 monterey: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
