# Auto-generated by update_formula.sh
class Opus < Formula
  desc "Audio codec"
  homepage "https://www.opus-codec.org/"
  version "1.6.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/opus--1.6.1.sequoia.bottle.tar.gz"
  sha256 "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
    sha256 ventura: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
    sha256 monterey: "09e6fa0ed569da4d6a63f5dde7839b9854bfab33cb35061399437fffde2f1611"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
