# Auto-generated by update_formula.sh
class Pcre2 < Formula
  desc "Perl compatible regular expressions library with a new API"
  homepage "https://www.pcre.org/"
  version "10.47_1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/pcre2--10.47_1.sequoia.bottle.tar.gz"
  sha256 "7c3c8861844abbe40048a8aeab8b4cbb74e6bbe13af4edf6f28cdea64aaf97dd"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "7c3c8861844abbe40048a8aeab8b4cbb74e6bbe13af4edf6f28cdea64aaf97dd"
    sha256 ventura: "7c3c8861844abbe40048a8aeab8b4cbb74e6bbe13af4edf6f28cdea64aaf97dd"
    sha256 monterey: "7c3c8861844abbe40048a8aeab8b4cbb74e6bbe13af4edf6f28cdea64aaf97dd"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
