# Auto-generated by update_formula.sh
class Upcre2 < Formula
  desc "Perl compatible regular expressions library with a new API"
  homepage "https://www.pcre.org/"
  version "10.47_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/pcre2--10.47_1.sequoia.bottle.tar.gz"
  sha256 "45b83e1da18dc350295a6be4b82f333170771819e5fe2fae97f4f1b45aece260"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "45b83e1da18dc350295a6be4b82f333170771819e5fe2fae97f4f1b45aece260"
    sha256 ventura: "45b83e1da18dc350295a6be4b82f333170771819e5fe2fae97f4f1b45aece260"
    sha256 monterey: "45b83e1da18dc350295a6be4b82f333170771819e5fe2fae97f4f1b45aece260"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
