# Auto-generated by update_formula.sh
class Pkgconf < Formula
  desc "Package compiler and linker metadata toolkit"
  homepage "https://github.com/pkgconf/pkgconf"
  version "2.5.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/pkgconf--2.5.1.sequoia.bottle.tar.gz"
  sha256 "91df9660bfc250306c6fc9c51b75f23cc6855f212769c2e4425b33c9261314ac"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "91df9660bfc250306c6fc9c51b75f23cc6855f212769c2e4425b33c9261314ac"
    sha256 ventura: "91df9660bfc250306c6fc9c51b75f23cc6855f212769c2e4425b33c9261314ac"
    sha256 monterey: "91df9660bfc250306c6fc9c51b75f23cc6855f212769c2e4425b33c9261314ac"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
