# Auto-generated by update_formula.sh
class UpythonAt3.14 < Formula
  desc "Interpreted, interactive, object-oriented programming language"
  homepage "https://www.python.org/"
  version "3.14.3_1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/python@3.14--3.14.3_1.sequoia.bottle.tar.gz"
  sha256 "6fa8835e3070e9d427b4dd0a8a26b82f9da14b6a125f95bc20120ab1bf7c30f9"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "6fa8835e3070e9d427b4dd0a8a26b82f9da14b6a125f95bc20120ab1bf7c30f9"
    sha256 ventura: "6fa8835e3070e9d427b4dd0a8a26b82f9da14b6a125f95bc20120ab1bf7c30f9"
    sha256 monterey: "6fa8835e3070e9d427b4dd0a8a26b82f9da14b6a125f95bc20120ab1bf7c30f9"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
