# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-29 09:38:28 UTC
class rclone < Formula
  desc "Rsync for cloud storage"
  homepage "https://rclone.org/"
  version "1.73.3"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/rclone-1.73.3.sequoia.bottle.1.tar.gz"
  sha256 "7e208f3877a7b094ccb98141b7dcef785b06bd945281d1d74e2d0f4ba3f272a2"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "7e208f3877a7b094ccb98141b7dcef785b06bd945281d1d74e2d0f4ba3f272a2"
    sha256 ventura:  "7e208f3877a7b094ccb98141b7dcef785b06bd945281d1d74e2d0f4ba3f272a2"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/rclone", "--version"
  end
end
