# Auto-generated by update_formula.sh
class Readline < Formula
  desc "Library for command-line editing"
  homepage "https://tiswww.case.edu/php/chet/readline/rltop.html"
  version "8.3.3"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/readline--8.3.3.sequoia.bottle.1.tar.gz"
  sha256 "2b76dba1dacca6a1e69c418a1589e075168755ff728042134f969e44f269d04d"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
