# Auto-generated by update_formula.sh
class Urust < Formula
  desc "Safe, concurrent, practical language"
  homepage "https://www.rust-lang.org/"
  version "1.94.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/rust--1.94.1.sequoia.bottle.tar.gz"
  sha256 "35997aa118a62bff2c1fc151a4bdc78be15fc18bf04b63eee56a010af2fd69da"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "35997aa118a62bff2c1fc151a4bdc78be15fc18bf04b63eee56a010af2fd69da"
    sha256 ventura: "35997aa118a62bff2c1fc151a4bdc78be15fc18bf04b63eee56a010af2fd69da"
    sha256 monterey: "35997aa118a62bff2c1fc151a4bdc78be15fc18bf04b63eee56a010af2fd69da"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
