# Auto-generated by update_formula.sh
class Usdl2 < Formula
  desc "Low-level access to audio, keyboard, mouse, joystick, and graphics"
  homepage "https://www.libsdl.org/"
  version "2.32.10"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/sdl2--2.32.10.sequoia.bottle.tar.gz"
  sha256 "16e5d569f8c2bebaaf316ac65a0a219d0c092e9f4aa2910fc2cc4a8baa9bbc1c"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "16e5d569f8c2bebaaf316ac65a0a219d0c092e9f4aa2910fc2cc4a8baa9bbc1c"
    sha256 ventura: "16e5d569f8c2bebaaf316ac65a0a219d0c092e9f4aa2910fc2cc4a8baa9bbc1c"
    sha256 monterey: "16e5d569f8c2bebaaf316ac65a0a219d0c092e9f4aa2910fc2cc4a8baa9bbc1c"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
