# Auto-generated by update_formula.sh
class UsphinxUdoc < Formula
  desc "Tool to create intelligent and beautiful documentation"
  homepage "https://www.sphinx-doc.org/"
  version "9.1.0_3"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/sphinx-doc--9.1.0_3.sequoia.bottle.tar.gz"
  sha256 "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
    sha256 ventura: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
    sha256 monterey: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
