# Auto-generated by update_formula.sh
class SphinxDoc < Formula
  desc "Tool to create intelligent and beautiful documentation"
  homepage "https://www.sphinx-doc.org/"
  version "9.1.0_3"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/sphinx-doc--9.1.0_3.sequoia.bottle.tar.gz"
  sha256 "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
    sha256 ventura: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
    sha256 monterey: "68c4b91cf904fe927386be68d8ada6f9466242a826914bda0f5f3921cf367ef0"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
