# Auto-generated by update_formula.sh
class UsvtUav1 < Formula
  desc "AV1 encoder"
  homepage "https://gitlab.com/AOMediaCodec/SVT-AV1"
  version "4.1.0"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/svt-av1--4.1.0.sequoia.bottle.tar.gz"
  sha256 "5599697dd03e17b3ce57d16a44c34674fcf932dc9487eb7b45f5eb99d90eba8e"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "5599697dd03e17b3ce57d16a44c34674fcf932dc9487eb7b45f5eb99d90eba8e"
    sha256 ventura: "5599697dd03e17b3ce57d16a44c34674fcf932dc9487eb7b45f5eb99d90eba8e"
    sha256 monterey: "5599697dd03e17b3ce57d16a44c34674fcf932dc9487eb7b45f5eb99d90eba8e"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
