# Auto-generated by update_formula.sh
class SvtAv1 < Formula
  desc "AV1 encoder"
  homepage "https://gitlab.com/AOMediaCodec/SVT-AV1"
  version "4.1.0"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/svt-av1--4.1.0.sequoia.bottle.1.tar.gz"
  sha256 "3ea17d13f556f49bff956ba8ae7687a67b1d3c405be5e1401269f602570ec6b4"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
