# Auto-generated by update_formula.sh
class Swig < Formula
  desc "Generate scripting interfaces to C/C++ code"
  homepage "https://www.swig.org/"
  version "4.4.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/swig--4.4.1.sequoia.bottle.tar.gz"
  sha256 "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
    sha256 ventura: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
    sha256 monterey: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
