# Auto-generated by update_formula.sh
class Uswig < Formula
  desc "Generate scripting interfaces to C/C++ code"
  homepage "https://www.swig.org/"
  version "4.4.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/swig--4.4.1.sequoia.bottle.tar.gz"
  sha256 "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
    sha256 ventura: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
    sha256 monterey: "a912411daa54354300c827677281019ce6b624965a0d7a70a4898b1c8b552bab"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
