# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-28 16:40:29 UTC
class tmux < Formula
  desc "Terminal multiplexer"
  homepage "https://tmux.github.io/"
  version "3.6a"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/tmux-3.6a.sequoia.bottle.1.tar.gz"
  sha256 "971b1028c02f0ed7034b610f1791fe228ffd725ee1b30e4203fb70f483bdaab0"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "971b1028c02f0ed7034b610f1791fe228ffd725ee1b30e4203fb70f483bdaab0"
    sha256 ventura:  "971b1028c02f0ed7034b610f1791fe228ffd725ee1b30e4203fb70f483bdaab0"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/tmux", "--version"
  end
end
