# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-29 09:38:29 UTC
class tree < Formula
  desc "Display directories as trees (with optional color/HTML output)"
  homepage "https://oldmanprogrammer.net/source.php?dir=projects/tree"
  version "2.3.2"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/tree-2.3.2.sequoia.bottle.1.tar.gz"
  sha256 "6549546997090e952d1d9cf834dfa5651db0f28001eb852a9e11fe4d524ed3da"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "6549546997090e952d1d9cf834dfa5651db0f28001eb852a9e11fe4d524ed3da"
    sha256 ventura:  "6549546997090e952d1d9cf834dfa5651db0f28001eb852a9e11fe4d524ed3da"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/tree", "--version"
  end
end
