# Auto-generated by update_formula.sh
class Tree < Formula
  desc "Display directories as trees (with optional color/HTML output)"
  homepage "https://oldmanprogrammer.net/source.php?dir=projects/tree"
  version "2.3.2"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/tree--2.3.2.sequoia.bottle.tar.gz"
  sha256 "b67bd5c66cce5aceb5357c4961b6240f39fd17e426bc48dc94d1c8cac212f147"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "b67bd5c66cce5aceb5357c4961b6240f39fd17e426bc48dc94d1c8cac212f147"
    sha256 ventura: "b67bd5c66cce5aceb5357c4961b6240f39fd17e426bc48dc94d1c8cac212f147"
    sha256 monterey: "b67bd5c66cce5aceb5357c4961b6240f39fd17e426bc48dc94d1c8cac212f147"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
