# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-31 02:36:02 UTC
class tree < Formula
  desc "Display directories as trees (with optional color/HTML output)"
  homepage "https://oldmanprogrammer.net/source.php?dir=projects/tree"
  version "2.3.2"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/tree-2.3.2.sequoia.bottle.1.tar.gz"
  sha256 "380a252ed35753c63f6f4e43f063cb966d147db2edd4f3b2d3aced119c544f28"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "380a252ed35753c63f6f4e43f063cb966d147db2edd4f3b2d3aced119c544f28"
    sha256 ventura:  "380a252ed35753c63f6f4e43f063cb966d147db2edd4f3b2d3aced119c544f28"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/tree", "--version"
  end
end
