# Auto-generated by update_formula.sh
class Uuvwasi < Formula
  desc "WASI syscall API built atop libuv"
  homepage "https://github.com/nodejs/uvwasi"
  version "0.0.23"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/uvwasi--0.0.23.sequoia.bottle.tar.gz"
  sha256 "d2e53dcf507d81e99625db3914aa1af69a2242c427426a07e3bf4c9ae4dda989"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "d2e53dcf507d81e99625db3914aa1af69a2242c427426a07e3bf4c9ae4dda989"
    sha256 ventura: "d2e53dcf507d81e99625db3914aa1af69a2242c427426a07e3bf4c9ae4dda989"
    sha256 monterey: "d2e53dcf507d81e99625db3914aa1af69a2242c427426a07e3bf4c9ae4dda989"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
