# Auto-generated by update_formula.sh — DO NOT EDIT MANUALLY
# Last updated: 2026-03-29 09:38:29 UTC
class wget < Formula
  desc "Internet file retriever"
  homepage "https://www.gnu.org/software/wget/"
  version "1.25.0"
  # No source URL needed — install via bottle only
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/wget-1.25.0.sequoia.bottle.2.tar.gz"
  sha256 "3a80c4fd34e0540e9c57e00b567f41f42e90dc57c50bb7a0d6a8adb68aa6a1a7"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    sha256 monterey: "3a80c4fd34e0540e9c57e00b567f41f42e90dc57c50bb7a0d6a8adb68aa6a1a7"
    sha256 ventura:  "3a80c4fd34e0540e9c57e00b567f41f42e90dc57c50bb7a0d6a8adb68aa6a1a7"
  end

  def install
    # Bottle installation is handled automatically by Homebrew
  end

  test do
    system "#{bin}/wget", "--version"
  end
end
