# Auto-generated by update_formula.sh
class X264 < Formula
  desc "H.264/AVC encoder"
  homepage "https://www.videolan.org/developers/x264.html"
  version "r3222"
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/x264--r3222.sequoia.bottle.1.tar.gz"
  sha256 "e527149ca7c80b34a40bca8d403f83ed3c2cb50975c5ff8a6af6a2d3a0f6d73d"



  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
