# Auto-generated by update_formula.sh
class X265 < Formula
  desc "H.265/HEVC encoder"
  homepage "https://bitbucket.org/multicoreware/x265_git"
  version "4.1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/x265--4.1.sequoia.bottle.tar.gz"
  sha256 "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
    sha256 ventura: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
    sha256 monterey: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
