# Auto-generated by update_formula.sh
class Ux265 < Formula
  desc "H.265/HEVC encoder"
  homepage "https://bitbucket.org/multicoreware/x265_git"
  version "4.1"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/x265--4.1.sequoia.bottle.tar.gz"
  sha256 "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
    sha256 ventura: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
    sha256 monterey: "b2e204333464e8e5109ee367394503f1e6c0728ac7e3f146750ef97a189b04a1"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
