# Auto-generated by update_formula.sh
class Uxz < Formula
  desc "General-purpose data compression with high compression ratio"
  homepage "https://tukaani.org/xz/"
  version "5.8.3"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/xz--5.8.3.sequoia.bottle.tar.gz"
  sha256 "9c0a0d3aedc2dfbc087c4497fb1957064f0582721b33c023a105babc52cfb0ff"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "9c0a0d3aedc2dfbc087c4497fb1957064f0582721b33c023a105babc52cfb0ff"
    sha256 ventura: "9c0a0d3aedc2dfbc087c4497fb1957064f0582721b33c023a105babc52cfb0ff"
    sha256 monterey: "9c0a0d3aedc2dfbc087c4497fb1957064f0582721b33c023a105babc52cfb0ff"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
