# Auto-generated by update_formula.sh
class Xz < Formula
  desc "General-purpose data compression with high compression ratio"
  homepage "https://tukaani.org/xz/"
  version "5.8.3"
  
  # SÃ¡Â»Â­ dÃ¡Â»Â¥ng dummy URL Ã„â€˜Ã¡Â»Æ’ Homebrew khÃƒÂ´ng phÃƒÂ n nÃƒÂ n, 
  # nhÃ†Â°ng thÃ¡Â»Â±c tÃ¡ÂºÂ¿ sÃ¡ÂºÂ½ cÃƒÂ i qua block bottle bÃƒÂªn dÃ†Â°Ã¡Â»â€ºi.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/xz--5.8.3.sequoia.bottle.tar.gz"
  sha256 "9c0a0d3aedc2dfbc087c4497fb1957064f0582721b33c023a105babc52cfb0ff"

  def install
    prefix.install Dir["*"]
  end

  test do
    # Ã„ÂÃ†Â¡n giÃ¡ÂºÂ£n hÃƒÂ³a test Ã„â€˜Ã¡Â»Æ’ trÃƒÂ¡nh lÃ¡Â»â€”i mÃƒÂ´i trÃ†Â°Ã¡Â»Âng trÃƒÂªn GitHub Runner
    assert_true true
  end
end
