# Auto-generated by update_formula.sh
class Uyasm < Formula
  desc "Modular BSD reimplementation of NASM"
  homepage "https://www.tortall.net/projects/yasm/manual/html/"
  version "1.3.0_2"
  
  # Sử dụng dummy URL để Homebrew không phàn nàn, 
  # nhưng thực tế sẽ cài qua block bottle bên dưới.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/yasm--1.3.0_2.sequoia.bottle.tar.gz"
  sha256 "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lừa" Homebrew: Dùng cùng một bản build Sequoia cho các bản OS cũ hơn
    sha256 sequoia: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
    sha256 ventura: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
    sha256 monterey: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
  end

  def install
    # Homebrew sẽ tự động giải nén bottle vào Cellar
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
