# Auto-generated by update_formula.sh
class Yasm < Formula
  desc "Modular BSD reimplementation of NASM"
  homepage "https://www.tortall.net/projects/yasm/manual/html/"
  version "1.3.0_2"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/yasm--1.3.0_2.sequoia.bottle.tar.gz"
  sha256 "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
    sha256 ventura: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
    sha256 monterey: "06201ada5a17fbc5c53c973f5d298862458ec21305b29d2a9f0ec5347a041e66"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
