# Auto-generated by update_formula.sh
class YtDlp < Formula
  desc "Feature-rich command-line audio/video downloader"
  homepage "https://github.com/yt-dlp/yt-dlp"
  version "2026.3.17_1"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/yt-dlp--2026.3.17_1.sequoia.bottle.tar.gz"
  sha256 "26aec87bd18a15bb2e0955cf8785f5da4defb50c315b119cc7288fa47f264a72"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "26aec87bd18a15bb2e0955cf8785f5da4defb50c315b119cc7288fa47f264a72"
    sha256 ventura: "26aec87bd18a15bb2e0955cf8785f5da4defb50c315b119cc7288fa47f264a72"
    sha256 monterey: "26aec87bd18a15bb2e0955cf8785f5da4defb50c315b119cc7288fa47f264a72"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
