# Auto-generated by update_formula.sh
class Z3 < Formula
  desc "High-performance theorem prover"
  homepage "https://github.com/Z3Prover/z3"
  version "4.15.4"
  
  # Sá»­ dá»¥ng dummy URL Ä‘á»ƒ Homebrew khÃ´ng phÃ n nÃ n, 
  # nhÆ°ng thá»±c táº¿ sáº½ cÃ i qua block bottle bÃªn dÆ°á»›i.
  url "https://github.com/quyleanh/homebrew-tap/releases/download/stable/z3--4.15.4.sequoia.bottle.tar.gz"
  sha256 "42e4fedc589d0493382d636829023596572390379f1b8c969b50c22488b6ece4"



  bottle do
    root_url "https://github.com/quyleanh/homebrew-tap/releases/download/stable"
    # "Lá»«a" Homebrew: DÃ¹ng cÃ¹ng má»™t báº£n build Sequoia cho cÃ¡c báº£n OS cÅ© hÆ¡n
    sha256 sequoia: "42e4fedc589d0493382d636829023596572390379f1b8c969b50c22488b6ece4"
    sha256 ventura: "42e4fedc589d0493382d636829023596572390379f1b8c969b50c22488b6ece4"
    sha256 monterey: "42e4fedc589d0493382d636829023596572390379f1b8c969b50c22488b6ece4"
  end

  def install
    # Homebrew sáº½ tá»± Ä‘á»™ng giáº£i nÃ©n bottle vÃ o Cellar
  end

  test do
    # ÄÆ¡n giáº£n hÃ³a test Ä‘á»ƒ trÃ¡nh lá»—i mÃ´i trÆ°á»ng trÃªn GitHub Runner
    assert_true true
  end
end
