#!/usr/bin/env bash

# build.sh — Resolve full dependency graph then build Homebrew bottles

# in topological order so each dependency is available before its dependents.

# 

# Flow:

# 1. Read top-level packages from packages.txt

# 2. Run `brew deps` to resolve the full graph (writes packages_resolved.txt)

# 3. Topological sort via `brew deps --topological`

# 4. Build + bottle each package; skip if already up to date in the release

# 

# Runs on GitHub Actions macos-15-intel (Sequoia, Intel x86_64).

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
SCRIPT_DIR="$(cd "$SCRIPT_DIR" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PACKAGES_FILE="$REPO_ROOT/packages.txt"
RESOLVED_FILE="$REPO_ROOT/packages_resolved.txt"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/bottles}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-}"
FORCE_BUILD="${FORCE_BUILD:-false}"
MAX_BUILD_TIME=$((5 * 3600)) # 5 hours in seconds
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-12.0}"

mkdir -p "$OUTPUT_DIR"

echo "=== Homebrew Bottle Builder ==="
echo "Output dir  : $OUTPUT_DIR"
echo "Force build : ${FORCE_BUILD}"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 1: Read top-level packages

# ──────────────────────────────────────────────────────────────

mapfile -t LEAVES < <(awk '!/^[ \t]*#/ && !/^[ \t]*$/' "$PACKAGES_FILE")

echo "📋 Top-level packages (${#LEAVES[@]}):"
printf '  %s\n' "${LEAVES[@]}"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 2: Resolve full dependency graph using brew deps

# brew deps --topological prints dependencies before dependents

# --include-build includes build-time deps (needed on CI)

# ──────────────────────────────────────────────────────────────

echo "🔍 Resolving full dependency graph…"

resolve_ordered() {
local leaves=("$@")

# Collect all unique deps in topological order for the full set

# brew deps --topological on multiple packages gives the right order

all_deps=$(brew deps --topological --union "${leaves[@]}" 2>/dev/null |
awk '!/^[ \t]*$/' |
awk '!seen[$0]++')

# Build the final ordered list:

# 1. Dependencies first (topological order)

# 2. Then leaves that weren't already listed as a dep of something else

{
echo "$all_deps"
printf '%s\n' "${leaves[@]}"
} | awk '!/^[ \t]*$/' | awk '!seen[$0]++'
}

mapfile -t ORDERED < <(resolve_ordered "${LEAVES[@]}")

echo "📦 Resolved build order (${#ORDERED[@]} total packages):"
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
if $is_leaf; then
echo "  $pkg  [leaf]"
else
echo "  $pkg"
fi
done
echo ""

# Write resolved list to file for reference / debugging

{
echo "# packages_resolved.txt — auto-generated by build.sh"
echo "# Do not edit manually. Edit packages.txt instead."
echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "# Total: ${#ORDERED[@]} packages (${#LEAVES[@]} leaves + dependencies)"
echo ""
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
$is_leaf && echo "$pkg  # [leaf]" || echo "$pkg"
done
} > "$RESOLVED_FILE"

echo "📝 Resolved list written to: packages_resolved.txt"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 3: Version cache (temp files, bash 3.2 compatible)

# ──────────────────────────────────────────────────────────────

VERSIONS_CACHE_DIR="$(mktemp -d)"

fetch_released_versions() {
if [ -z "$GITHUB_REPOSITORY" ]; then
echo "⚠️  GITHUB_REPOSITORY not set — will build all packages"
return
fi

echo "🔍 Fetching released asset list from GitHub using gh CLI…"
export GH_TOKEN="${GITHUB_TOKEN:-}"

# Use gh feature to fetch ALL assets instead of just the first 30 (curl pagination limit)
local assets
assets=$(gh release view stable --repo "$GITHUB_REPOSITORY" --json assets --jq '.assets[].name' 2>/dev/null) || {
echo "⚠️  Could not fetch release info — will build all packages"
return
}

while IFS= read -r asset_name; do
# Bottle filename format examples: 
# aria2--1.37.0_1.sequoia.bottle.tar.gz
# aria2--1.37.0.intel_12.bottle.tar.gz
if [[ "$asset_name" =~ ^([a-zA-Z0-9_@.-]+)--([^/]+)\.(sequoia|ventura|sonoma|monterey|big_sur|intel[0-9_]*)\. ]]; then
local pkg="${BASH_REMATCH[1]}"
local ver="${BASH_REMATCH[2]}"
echo "$ver" > "$VERSIONS_CACHE_DIR/$pkg"
echo "  $pkg @ $ver"
fi
done <<< "$assets"

echo ""
}

get_released_version() {
local f="$VERSIONS_CACHE_DIR/$1"
[ -f "$f" ] && cat "$f" || echo ""
}

# ──────────────────────────────────────────────────────────────

# Step 4: Determine if a package needs rebuilding

# ──────────────────────────────────────────────────────────────

needs_build() {
local pkg="$1"

if [ "$FORCE_BUILD" = "true" ]; then
echo "  → Force build enabled"
return 0
fi

  local info
  info=$(brew info --json=v1 "$pkg" 2>/dev/null)
  
  local latest
  latest=$(echo "$info" | jq -r '.[0].versions.stable // empty')

  local revision
  revision=$(echo "$info" | jq -r '.[0].revision // 0' || echo "0")
  if [ "${revision:-0}" -gt 0 ]; then
    latest="${latest}_${revision}"
  fi

if [ -z "$latest" ]; then
echo "  → Could not determine version, building to be safe"
return 0
fi

local released
released=$(get_released_version "$pkg")

echo "  → Latest  : $latest"
echo "  → Released: ${released:-<none>}"

if [ -z "$released" ]; then
echo "  → Not in release yet, will build"
return 0
fi

if [ "$latest" = "$released" ]; then
echo "  → Up to date, skipping ✓"
return 1
fi

echo "  → New version available, will build"
return 0
}

# ──────────────────────────────────────────────────────────────

# Step 5: Build loop

# ──────────────────────────────────────────────────────────────

echo "🔄 Updating Homebrew…"
brew update --quiet
echo ""

fetch_released_versions

BUILT=()
SKIPPED=()
FAILED=()
START_TIME=$(date +%s)

for pkg in "${ORDERED[@]}"; do
CURRENT_TIME=$(date +%s)
ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

if [ "$ELAPSED_TIME" -gt "$MAX_BUILD_TIME" ]; then
  echo "──────────────────────────────────────"
  echo "⚠️ Time limit reached (5.5 hours). Stopping loop gracefully."
  echo "This saves our progress so the CI can commit formulas and releases."
  echo "Run the workflow again to pick up where it left off!"
  echo "──────────────────────────────────────"
  break
fi

echo "──────────────────────────────────────"
echo "📦 $pkg"
echo "──────────────────────────────────────"

if ! needs_build "$pkg"; then
SKIPPED+=("$pkg")
# Ensure package is installed locally so dependents can link against it
if ! brew list --formula "$pkg" &>/dev/null; then
  echo "  ℹ️  Installing locally so dependents can link..."
  brew install "$pkg" 2>/dev/null || true
else
  echo "  ℹ️  Already installed locally ✓"
fi

echo ""
continue

fi

# Uninstall for a clean build

brew uninstall --ignore-dependencies "$pkg" 2>/dev/null || true

if brew install --build-bottle "$pkg"; then
echo "  ✅ Installed, packing bottle…"

# Resolve actual Cellar path — may include revision suffix (_1, _2...)
cellar_path=$(ls -dt "$(brew --cellar)/$pkg/"*/ 2>/dev/null | head -1 | sed 's|/$||')
pkg_version=$(basename "$cellar_path")

if [ -z "$pkg_version" ] || [ ! -d "$cellar_path" ]; then
  echo "  ⚠️  Cellar path not found for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

echo "  📦 Packing bottle via Homebrew..."

# Let brew bottle generate BOTH the JSON and the deterministic tar.gz archive
# This ensures the SHA256 checksums mathematically match in the future!
brew bottle \
  --json \
  --root-url "https://github.com/${GITHUB_REPOSITORY}/releases/download/stable" \
  "$pkg" 2>/dev/null || true

# Move BOTH the natively generated tar.gz bottle and the JSON file to OUTPUT_DIR
# We find exactly what Homebrew generated to avoid hardcoding the OS tag (sequoia/ventura/etc)
find . -maxdepth 1 -name "${pkg}--*.json" -exec mv {} "$OUTPUT_DIR/" \;
find . -maxdepth 1 -name "${pkg}--*.tar.gz" -exec mv {} "$OUTPUT_DIR/" \;

# Find the tarball we just moved to verify it exists
bottle_path=$(find "$OUTPUT_DIR" -maxdepth 1 -name "${pkg}--*${pkg_version}*.tar.gz" | head -n 1)

if [ -z "$bottle_path" ] || [ ! -f "$bottle_path" ]; then
  echo "  ⚠️  brew bottle failed to generate the archive for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

echo "  ✅ Done: $pkg @ $pkg_version ($(du -h "$bottle_path" | cut -f1))"
BUILT+=("$pkg")

# Package stays installed in Cellar — next packages link against it for free

else
echo "  ❌ Build failed: $pkg"
FAILED+=("$pkg")
fi

echo ""
done

rm -rf "$VERSIONS_CACHE_DIR"

# ──────────────────────────────────────────────────────────────

# Summary

# ──────────────────────────────────────────────────────────────

echo "══════════════════════════════════════"
echo "Build Summary"
echo "══════════════════════════════════════"
echo "✅ Built   (${#BUILT[@]}): ${BUILT[*]:-none}"
echo "⏭️  Skipped (${#SKIPPED[@]}): ${SKIPPED[*]:-none}"
echo "❌ Failed  (${#FAILED[@]}): ${FAILED[*]:-none}"
echo ""

[ ${#BUILT[@]} -eq 0 ] && [ ${#FAILED[@]} -eq 0 ] &&   
echo "Nothing new to build — all packages are up to date."

ls -lh "$OUTPUT_DIR/"*.tar.gz 2>/dev/null || echo "No bottles in output dir."

echo "BUILT_COUNT=${#BUILT[@]}"   >> "${GITHUB_OUTPUT:-/dev/null}"
echo "FAILED_COUNT=${#FAILED[@]}" >> "${GITHUB_OUTPUT:-/dev/null}"

if [ ${#FAILED[@]} -gt 0 ]; then
echo ""
echo "⚠️  Some packages failed. Check logs above."
exit 1
fi
