#!/usr/bin/env bash

# build.sh — Resolve full dependency graph then build Homebrew bottles

# in topological order so each dependency is available before its dependents.

# 

# Flow:

# 1. Read top-level packages from packages.txt

# 2. Run `brew deps` to resolve the full graph (writes packages_resolved.txt)

# 3. Topological sort via `brew deps --topological`

# 4. Build + bottle each package; skip if already up to date in the release

# 

# Runs on GitHub Actions macos-15-intel (Sequoia, Intel x86_64).

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
SCRIPT_DIR="$(cd "$SCRIPT_DIR" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PACKAGES_FILE="$REPO_ROOT/packages.txt"
RESOLVED_FILE="$REPO_ROOT/packages_resolved.txt"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/bottles}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-}"
FORCE_BUILD="${FORCE_BUILD:-false}"
MAX_BUILD_TIME="${MAX_BUILD_TIME:-$((5 * 3600))}" # Default: 5 hours in seconds
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-13.0}"

mkdir -p "$OUTPUT_DIR"

echo "=== Homebrew Bottle Builder ==="
echo "Output dir     : $OUTPUT_DIR"
echo "Force build    : ${FORCE_BUILD}"
echo "Max build time : $((MAX_BUILD_TIME / 60)) minutes ($MAX_BUILD_TIME seconds)"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 1: Read top-level packages

# ──────────────────────────────────────────────────────────────

mapfile -t LEAVES < <(awk '!/^[ \t]*#/ && !/^[ \t]*$/' "$PACKAGES_FILE")

echo "📋 Top-level packages (${#LEAVES[@]}):"
printf '  %s\n' "${LEAVES[@]}"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 2: Resolve full dependency graph using brew deps

# brew deps --topological prints dependencies before dependents

# --include-build includes build-time deps (needed on CI)

# ──────────────────────────────────────────────────────────────

echo "🔍 Resolving full dependency graph…"

resolve_ordered() {
local leaves=("$@")

# Collect all unique deps in topological order for the full set

# brew deps --topological on multiple packages gives the right order

all_deps=$(brew deps --topological --union --include-build "${leaves[@]}" 2>/dev/null |
awk '!/^[ \t]*$/' |
awk '!seen[$0]++')

# Build the final ordered list:

# 1. Dependencies first (topological order)

# 2. Then leaves that weren't already listed as a dep of something else

{
echo "$all_deps"
printf '%s\n' "${leaves[@]}"
} | awk '!/^[ \t]*$/' | awk '!seen[$0]++'
}

mapfile -t ORDERED < <(resolve_ordered "${LEAVES[@]}")

echo "📦 Resolved build order (${#ORDERED[@]} total packages):"
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
if $is_leaf; then
echo "  $pkg  [leaf]"
else
echo "  $pkg"
fi
done
echo ""

# Write resolved list to file for reference / debugging

{
echo "# packages_resolved.txt — auto-generated by build.sh"
echo "# Do not edit manually. Edit packages.txt instead."
echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "# Total: ${#ORDERED[@]} packages (${#LEAVES[@]} leaves + dependencies)"
echo ""
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
$is_leaf && echo "$pkg  # [leaf]" || echo "$pkg"
done
} > "$RESOLVED_FILE"

echo "📝 Resolved list written to: packages_resolved.txt"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 3: Version cache (temp files, bash 3.2 compatible)

# ──────────────────────────────────────────────────────────────

VERSIONS_CACHE_DIR="$(mktemp -d)"
RELEASED_ASSETS_FILE="$(mktemp)"

fetch_released_versions() {
if [ -z "$GITHUB_REPOSITORY" ]; then
echo "⚠️  GITHUB_REPOSITORY not set — will build all packages"
return
fi

echo "🔍 Fetching released asset list from GitHub using gh CLI…"
export GH_TOKEN="${GITHUB_TOKEN:-}"

# Use gh feature to fetch ALL assets instead of just the first 30 (curl pagination limit)
local assets
assets=$(gh release view stable --repo "$GITHUB_REPOSITORY" --json assets --jq '.assets[].name' 2>/dev/null) || {
echo "⚠️  Could not fetch release info — will build all packages"
return
}

while IFS= read -r asset_name; do
[ -z "$asset_name" ] && continue
echo "$asset_name" >> "$RELEASED_ASSETS_FILE"
# Support both native ventura bottles (pkg-version.ventura.bottle.*) and runner bottles (pkg--version.tag...)
for pkg in "${ORDERED[@]}"; do
  if [[ "$asset_name" == "${pkg}-"* || "$asset_name" == "${pkg}--"* ]]; then
    rest="${asset_name#"${pkg}-"}"
    rest="${rest#"-"}"
    if [[ "$rest" =~ ^([0-9a-zA-Z_.-]+)\.(ventura|sequoia|sonoma|monterey|intel[0-9_]*)\.bottle ]]; then
      ver="${BASH_REMATCH[1]}"
      echo "$ver" > "$VERSIONS_CACHE_DIR/$pkg"
      echo "  $pkg @ $ver"
      break
    fi
  fi
done
done <<< "$assets"

echo ""
}

get_released_version() {
local f="$VERSIONS_CACHE_DIR/$1"
[ -f "$f" ] && cat "$f" || echo ""
}

has_released_bottle() {
local pkg="$1"
local version="$2"

while IFS= read -r asset_name; do
  [[ "$asset_name" == "$pkg-$version."*.tar.gz || "$asset_name" == "$pkg--$version."*.tar.gz ]] && return 0
done < "$RELEASED_ASSETS_FILE"

return 1
}

has_released_bottle_tag() {
local pkg="$1"
local version="$2"
local tag="$3"

while IFS= read -r asset_name; do
  [[ "$asset_name" == "$pkg-$version.$tag.bottle."*.tar.gz || "$asset_name" == "$pkg--$version.$tag.bottle."*.tar.gz ]] && return 0
done < "$RELEASED_ASSETS_FILE"

return 1
}

# ──────────────────────────────────────────────────────────────

# Step 4: Determine if a package needs rebuilding

# ──────────────────────────────────────────────────────────────

needs_build() {
local pkg="$1"
local formula_ref="$pkg"
[ "$pkg" = "ffmpeg" ] && formula_ref="quyleanh/tap/ffmpeg"
[ "$pkg" = "little-cms2" ] && formula_ref="homebrew/core/little-cms2"

if [ "$FORCE_BUILD" = "true" ]; then
echo "  → Force build enabled"
return 0
fi

  local info
  info=$(brew info --json=v1 "$formula_ref" 2>/dev/null)
  
  local latest
  latest=$(echo "$info" | jq -r '.[0].versions.stable // empty')

  local revision
  revision=$(echo "$info" | jq -r '.[0].revision // 0' || echo "0")
  if [ "${revision:-0}" -gt 0 ]; then
    latest="${latest}_${revision}"
  fi

if [ -z "$latest" ]; then
echo "  → Could not determine version, building to be safe"
return 0
fi

local released
released=$(get_released_version "$pkg")

echo "  → Latest  : $latest"
echo "  → Released: ${released:-<none>}"

if [ -z "$released" ]; then
echo "  → Not in release yet, will build"
return 0
fi

if [ "$latest" = "$released" ] && has_released_bottle "$pkg" "$latest"; then
  # A proper Ventura-tagged bottle is required for Homebrew to pour every
  # package during `brew upgrade` on the target macOS 13 machine.
  if ! has_released_bottle_tag "$pkg" "$latest" "ventura"; then
    echo "  → Missing Ventura bottle alias, will build"
    return 0
  fi
  echo "  → Up to date, skipping ✓"
  return 1
fi

if [ "$latest" = "$released" ]; then
echo "  → Matching version has no release bottle, will build"
return 0
fi

echo "  → New version available, will build"
return 0
}

# ──────────────────────────────────────────────────────────────
# Step 5: Immediate Package Publisher
# ──────────────────────────────────────────────────────────────

publish_package() {
  local pkg="$1"
  local pkg_version="$2"
  local bottle_file="$3"
  local json_file="${4:-}"

  # 1. Update the formula file locally
  if [ -n "$json_file" ] && [ -f "$json_file" ]; then
    echo "  📝 Generating Formula/${pkg}.rb..."
    BOTTLES_DIR="$OUTPUT_DIR" GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-}" \
      "$REPO_ROOT/scripts/update_formula.sh" "$json_file" || {
      echo "  ⚠️  Failed to generate formula for $pkg"
    }
  fi

  # 2. Upload to GitHub release immediately if GH_TOKEN & GITHUB_REPOSITORY are set
  local auth_token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
  if [ -n "$GITHUB_REPOSITORY" ] && [ -n "$auth_token" ]; then
    export GH_TOKEN="$auth_token"

    # Delete older version assets of this package from the GitHub Release
    echo "  🔍 Checking for older release assets of $pkg to clean up..."
    local remote_assets
    remote_assets=$(gh release view stable --repo "$GITHUB_REPOSITORY" --json assets --jq '.assets[].name' 2>/dev/null || echo "")

    if [ -n "$remote_assets" ]; then
      while IFS= read -r old_asset; do
        [ -z "$old_asset" ] && continue
        if [[ "$old_asset" == "${pkg}-"* || "$old_asset" == "${pkg}--"* ]]; then
          local rest="${old_asset#"${pkg}-"}"
          rest="${rest#"-"}"
          if [[ "$rest" =~ ^[0-9r][0-9a-zA-Z_.-]*\.(ventura|sequoia|sonoma|monterey|big_sur|intel[0-9_]*)\.bottle ]] || [[ "$rest" =~ ^[0-9r][0-9a-zA-Z_.-]*\.bottle ]]; then
            if [ "$old_asset" != "$(basename "$bottle_file")" ] && [ "$old_asset" != "$(basename "$json_file")" ]; then
              echo "  🗑️  Deleting older release asset: $old_asset"
              gh release delete-asset stable "$old_asset" --repo "$GITHUB_REPOSITORY" -y 2>/dev/null || true
            fi
          fi
        fi
      done <<< "$remote_assets"
    fi

    echo "  🚀 Uploading $pkg bottle to GitHub Release (stable)..."

    local upload_files=("$bottle_file")
    if [ -n "$json_file" ] && [ -f "$json_file" ]; then
      upload_files+=("$json_file")
    fi

    if gh release upload stable "${upload_files[@]}" --repo "$GITHUB_REPOSITORY" --clobber; then
      echo "  ✅ Bottle uploaded to GitHub Release"
      echo "$pkg_version" > "$VERSIONS_CACHE_DIR/$pkg"
      echo "$(basename "$bottle_file")" >> "$RELEASED_ASSETS_FILE"
    else
      echo "  ⚠️  Failed to upload bottle to GitHub Release"
    fi

    # 3. Commit and push formula update immediately
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add "$REPO_ROOT/Formula" "$RESOLVED_FILE"

    if ! git diff --staged --quiet; then
      echo "  💾 Committing & pushing formula update for $pkg..."
      git commit -m "chore(bottles): update $pkg ($pkg_version) [skip ci]

Built by GitHub Actions
Runner: macos-15-intel (Sequoia, Intel x86_64)" || true

      local push_success=false
      for attempt in 1 2 3; do
        if (git pull --rebase origin main 2>/dev/null || git pull --rebase 2>/dev/null) && (git push origin main 2>/dev/null || git push 2>/dev/null); then
          push_success=true
          echo "  ✅ Pushed commit for $pkg"
          break
        fi
        echo "  ⚠️  Push attempt $attempt failed, retrying in 3s..."
        sleep 3
      done
      if [ "$push_success" = false ]; then
        echo "  ⚠️  Could not push commit immediately. Will be pushed at workflow end."
      fi
    fi
  fi
}

# ──────────────────────────────────────────────────────────────
# Step 6: Build loop
# ──────────────────────────────────────────────────────────────

echo "🔄 Updating Homebrew…"
brew update --quiet
echo ""

fetch_released_versions

BUILT=()
SKIPPED=()
FAILED=()
START_TIME=$(date +%s)

for pkg in "${ORDERED[@]}"; do
CURRENT_TIME=$(date +%s)
ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

if [ "$ELAPSED_TIME" -gt "$MAX_BUILD_TIME" ]; then
  echo "──────────────────────────────────────"
  echo "⚠️ Time limit reached ($((MAX_BUILD_TIME / 60)) minutes elapsed). Stopping build loop gracefully."
  echo "This saves our progress so the CI can commit formulas and releases."
  echo "Run the workflow again to pick up where it left off!"
  echo "──────────────────────────────────────"
  break
fi

echo "──────────────────────────────────────"
echo "📦 $pkg (Elapsed: $((ELAPSED_TIME / 60))m / $((MAX_BUILD_TIME / 60))m)"
echo "──────────────────────────────────────"

formula_ref="$pkg"
[ "$pkg" = "ffmpeg" ] && formula_ref="quyleanh/tap/ffmpeg"
# This formula has a missing custom bottle. Build the maintained Homebrew Core
# source formula so the generated tap wrapper can restore it and its runtime
# dependency graph.
[ "$pkg" = "little-cms2" ] && formula_ref="homebrew/core/little-cms2"

if [ "$pkg" = "ffmpeg" ]; then
  tap_formula_dir="$(brew --repository quyleanh/tap 2>/dev/null)/Formula"
  if [ -d "$tap_formula_dir" ]; then
    cp "$REPO_ROOT/scripts/ffmpeg.rb" "$tap_formula_dir/ffmpeg.rb"
  else
    echo "  ❌ Registered quyleanh/tap directory not found"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
fi

if ! needs_build "$pkg"; then
SKIPPED+=("$pkg")
# Ensure package is installed locally so dependents can link against it
if ! brew list --formula "$pkg" &>/dev/null; then
  echo "  ℹ️  Installing locally so dependents can link..."
  brew install "$pkg" 2>/dev/null || true
else
  echo "  ℹ️  Already installed locally ✓"
fi

echo ""
continue

fi

# Uninstall for a clean build

brew uninstall --ignore-dependencies "$pkg" 2>/dev/null || true

if [ "$pkg" = "ffmpeg" ]; then
  formula_revision=$(brew info --json=v2 quyleanh/tap/ffmpeg 2>/dev/null |
    jq -r '.formulae[0].revision // 0')
  echo "  → FFmpeg formula revision: ${formula_revision:-unknown}"
  if [ "${formula_revision:-0}" -lt 4 ]; then
    echo "  ❌ Homebrew is not seeing FFmpeg revision 4; refusing stale formula build"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
fi

# Formulae must be installed by tap-qualified name; Homebrew rejects arbitrary
# workspace paths that are not registered as taps.
if brew install --build-bottle --overwrite "$formula_ref"; then
echo "  ✅ Installed, packing bottle…"

# Resolve actual Cellar path — may include revision suffix (_1, _2...)
cellar_path=$(ls -dt "$(brew --cellar)/$pkg/"*/ 2>/dev/null | head -1 | sed 's|/$||')
pkg_version=$(basename "$cellar_path")

if [ -z "$pkg_version" ] || [ ! -d "$cellar_path" ]; then
  echo "  ⚠️  Cellar path not found for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

# FFmpeg must remain usable on the user's macOS 13 Intel machine. Homebrew's
# macOS 15 linker can still emit LC_BUILD_VERSION=15 even when the actual
# deployment flags are lowered, so validate the incompatible symbol instead of
# rejecting the metadata alone.
if [ "$pkg" = "ffmpeg" ]; then
  ffmpeg_bin="$cellar_path/bin/ffmpeg"
  min_os=$(otool -l "$ffmpeg_bin" 2>/dev/null |
    awk '/LC_BUILD_VERSION/{seen=1; next} seen && /minos/{print $2; exit}')
  echo "  → FFmpeg minimum macOS: ${min_os:-unknown}"
  if nm -u "$cellar_path"/lib/*.dylib 2>/dev/null |
    grep -q "AVCaptureDeviceTypeContinuityCamera"; then
    echo "  ❌ FFmpeg still references the macOS 15-only AVFoundation symbol"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
  if [ -e "$cellar_path/lib/libavdevice.dylib" ] ||
    otool -L "$ffmpeg_bin" 2>/dev/null | grep -q '/libavdevice'; then
    echo "  ❌ FFmpeg still contains libavdevice; refusing to publish"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
  echo "  ✅ No macOS 15-only AVFoundation symbols detected"
fi

echo "  📦 Packing bottle via Homebrew..."

# Let brew bottle generate BOTH the JSON and the deterministic tar.gz archive
# This ensures the SHA256 checksums mathematically match in the future!
brew bottle \
  --json \
  --root-url "https://github.com/${GITHUB_REPOSITORY}/releases/download/stable" \
  "$pkg" 2>/dev/null || true

# Move BOTH the natively generated tar.gz bottle and the JSON file to OUTPUT_DIR
# We find exactly what Homebrew generated to avoid hardcoding the OS tag (sequoia/ventura/etc)
find . -maxdepth 1 -name "${pkg}--*.json" -exec mv {} "$OUTPUT_DIR/" \;
find . -maxdepth 1 -name "${pkg}--*.tar.gz" -exec mv {} "$OUTPUT_DIR/" \;

# Find the tarball we just moved to verify it exists
bottle_path=$(find "$OUTPUT_DIR" -maxdepth 1 -name "${pkg}--*${pkg_version}*.tar.gz" | head -n 1)

if [ -z "$bottle_path" ] || [ ! -f "$bottle_path" ]; then
  echo "  ⚠️  brew bottle failed to generate the archive for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

# Publish strictly Ventura-tagged bottles for macOS 13+.
# Rename the runner's bottle archive and JSON metadata to the native Ventura naming format
# so only Ventura bottles are uploaded to the release.
ventura_bottle_path="$OUTPUT_DIR/${pkg}-${pkg_version}.ventura.bottle.1.tar.gz"
mv "$bottle_path" "$ventura_bottle_path"

json_path=$(find "$OUTPUT_DIR" -maxdepth 1 -name "${pkg}--*${pkg_version}*.json" | head -n 1)
if [ -n "$json_path" ] && [ -f "$json_path" ]; then
  ventura_json_path="$OUTPUT_DIR/${pkg}-${pkg_version}.ventura.bottle.json"
  mv "$json_path" "$ventura_json_path"
fi

echo "  ✅ Done: $pkg @ $pkg_version ($(du -h "$ventura_bottle_path" | cut -f1))"
BUILT+=("$pkg")

# Immediately publish bottle to GitHub Release and push formula update to git
publish_package "$pkg" "$pkg_version" "$ventura_bottle_path" "${ventura_json_path:-}"

# Package stays installed in Cellar — next packages link against it for free

else
echo "  ❌ Build failed: $pkg"
FAILED+=("$pkg")
fi

echo ""
done

rm -rf "$VERSIONS_CACHE_DIR" "$RELEASED_ASSETS_FILE"

# ──────────────────────────────────────────────────────────────

# Summary

# ──────────────────────────────────────────────────────────────

echo "══════════════════════════════════════"
echo "Build Summary"
echo "══════════════════════════════════════"
echo "✅ Built   (${#BUILT[@]}): ${BUILT[*]:-none}"
echo "⏭️  Skipped (${#SKIPPED[@]}): ${SKIPPED[*]:-none}"
echo "❌ Failed  (${#FAILED[@]}): ${FAILED[*]:-none}"
echo ""

[ ${#BUILT[@]} -eq 0 ] && [ ${#FAILED[@]} -eq 0 ] &&   
echo "Nothing new to build — all packages are up to date."

ls -lh "$OUTPUT_DIR/"*.tar.gz 2>/dev/null || echo "No bottles in output dir."

echo "BUILT_COUNT=${#BUILT[@]}"   >> "${GITHUB_OUTPUT:-/dev/null}"
echo "FAILED_COUNT=${#FAILED[@]}" >> "${GITHUB_OUTPUT:-/dev/null}"

if [ ${#FAILED[@]} -gt 0 ]; then
echo ""
echo "⚠️  Some packages failed. Check logs above."
exit 1
fi
