#!/usr/bin/env bash

# build.sh — Resolve full dependency graph then build Homebrew bottles

# in topological order so each dependency is available before its dependents.

# 

# Flow:

# 1. Read top-level packages from packages.txt

# 2. Run `brew deps` to resolve the full graph (writes packages_resolved.txt)

# 3. Topological sort via `brew deps --topological`

# 4. Build + bottle each package; skip if already up to date in the release

# 

# Runs on GitHub Actions macos-15-intel (Sequoia, Intel x86_64).

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
SCRIPT_DIR="$(cd "$SCRIPT_DIR" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PACKAGES_FILE="$REPO_ROOT/packages.txt"
RESOLVED_FILE="$REPO_ROOT/packages_resolved.txt"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/bottles}"
BUILD_TIME_ESTIMATES_FILE="$REPO_ROOT/.github/build-times.tsv"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-}"
FORCE_BUILD="${FORCE_BUILD:-false}"
MAX_BUILD_TIME="${MAX_BUILD_TIME:-$((5 * 3600))}" # Default: 5 hours in seconds
DEFAULT_BUILD_ESTIMATE_SECONDS="${DEFAULT_BUILD_ESTIMATE_SECONDS:-3600}"
BUILD_TIME_RESERVE_SECONDS="${BUILD_TIME_RESERVE_SECONDS:-1200}"
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-13.0}"

mkdir -p "$OUTPUT_DIR"

echo "=== Homebrew Bottle Builder ==="
echo "Output dir     : $OUTPUT_DIR"
echo "Force build    : ${FORCE_BUILD}"
echo "Max build time : $((MAX_BUILD_TIME / 60)) minutes ($MAX_BUILD_TIME seconds)"
echo "Publish reserve: $((BUILD_TIME_RESERVE_SECONDS / 60)) minutes"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 1: Read top-level packages

# ──────────────────────────────────────────────────────────────

mapfile -t LEAVES < <(awk '!/^[ \t]*#/ && !/^[ \t]*$/' "$PACKAGES_FILE")

echo "📋 Top-level packages (${#LEAVES[@]}):"
printf '  %s\n' "${LEAVES[@]}"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 2: Resolve full dependency graph using brew deps

# brew deps --topological prints dependencies before dependents

# --include-build includes build-time deps (needed on CI)

# ──────────────────────────────────────────────────────────────

echo "🔍 Resolving full dependency graph…"

resolve_ordered() {
local leaves=("$@")

# Collect all unique deps in topological order for the full set

# brew deps --topological on multiple packages gives the right order

all_deps=$(brew deps --topological --union --include-build "${leaves[@]}" 2>/dev/null |
awk '!/^[ \t]*$/' |
awk '!seen[$0]++')

# Build the final ordered list:

# 1. Dependencies first (topological order)

# 2. Then leaves that weren't already listed as a dep of something else

{
echo "$all_deps"
printf '%s\n' "${leaves[@]}"
} | awk '!/^[ \t]*$/' | awk '!seen[$0]++'
}

mapfile -t ORDERED < <(resolve_ordered "${LEAVES[@]}")

echo "📦 Resolved build order (${#ORDERED[@]} total packages):"
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
if $is_leaf; then
echo "  $pkg  [leaf]"
else
echo "  $pkg"
fi
done
echo ""

# Write resolved list to file for reference / debugging

{
echo "# packages_resolved.txt — auto-generated by build.sh"
echo "# Do not edit manually. Edit packages.txt instead."
echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "# Total: ${#ORDERED[@]} packages (${#LEAVES[@]} leaves + dependencies)"
echo ""
for pkg in "${ORDERED[@]}"; do
is_leaf=false
for leaf in "${LEAVES[@]}"; do
[ "$pkg" = "$leaf" ] && is_leaf=true && break
done
$is_leaf && echo "$pkg  # [leaf]" || echo "$pkg"
done
} > "$RESOLVED_FILE"

echo "📝 Resolved list written to: packages_resolved.txt"
echo ""

# ──────────────────────────────────────────────────────────────

# Step 3: Version cache (temp files, bash 3.2 compatible)

# ──────────────────────────────────────────────────────────────

VERSIONS_CACHE_DIR="$(mktemp -d)"
RELEASED_ASSETS_FILE="$(mktemp)"
RELEASED_ASSET_DIGESTS_FILE="$(mktemp)"

fetch_released_versions() {
if [ -z "$GITHUB_REPOSITORY" ]; then
echo "⚠️  GITHUB_REPOSITORY not set — will build all packages"
return
fi

echo "🔍 Fetching released asset list from GitHub using gh CLI…"
export GH_TOKEN="${GITHUB_TOKEN:-}"

# Fetch names and server-computed digests in one request. The digest lets us
# reject a stale formula checksum before Homebrew downloads the archive.
local asset_rows
asset_rows=$(gh api "repos/$GITHUB_REPOSITORY/releases/tags/stable" \
  --jq '.assets[] | [.name, (.digest // "")] | @tsv' 2>/dev/null) || {
echo "⚠️  Could not fetch release info — will build all packages"
return
}

# Sort candidate packages by length in descending order so longer names (e.g. go-md2man, docker-compose)
# are evaluated before their prefix sub-names (e.g. go, docker).
local sorted_pkgs=()
mapfile -t sorted_pkgs < <(for p in "${ORDERED[@]}"; do echo "$p"; done | awk '{ print length, $0 }' | sort -rn | cut -d" " -f2-)

while IFS=$'\t' read -r asset_name asset_digest; do
[ -z "$asset_name" ] && continue
echo "$asset_name" >> "$RELEASED_ASSETS_FILE"
printf '%s\t%s\n' "$asset_name" "$asset_digest" >> "$RELEASED_ASSET_DIGESTS_FILE"
# Support both native ventura bottles (pkg-version.ventura.bottle.*) and runner bottles (pkg--version.tag...)
for pkg in "${sorted_pkgs[@]}"; do
  if [[ "$asset_name" == "${pkg}-"* || "$asset_name" == "${pkg}--"* ]]; then
    rest="${asset_name#"${pkg}-"}"
    rest="${rest#"-"}"
    # Version must start with a digit (e.g. 1.26.6, 2026-08-13) or 'r' followed by a digit (e.g. r3222)
    if [[ "$rest" =~ ^(([0-9]+|r[0-9]+)[0-9a-zA-Z_+.~-]*)\.(ventura|sequoia|sonoma|monterey|big_sur|intel[0-9_]*)\.bottle ]]; then
      ver="${BASH_REMATCH[1]}"
      echo "$ver" > "$VERSIONS_CACHE_DIR/$pkg"
      echo "  $pkg @ $ver"
      break
    fi
  fi
done
done <<< "$asset_rows"

echo ""
}

get_released_version() {
local f="$VERSIONS_CACHE_DIR/$1"
[ -f "$f" ] && cat "$f" || echo ""
}

has_released_bottle() {
local pkg="$1"
local version="$2"

while IFS= read -r asset_name; do
  [[ "$asset_name" == "$pkg-$version."*.tar.gz || "$asset_name" == "$pkg--$version."*.tar.gz ]] && return 0
done < "$RELEASED_ASSETS_FILE"

return 1
}

has_released_bottle_tag() {
local pkg="$1"
local version="$2"
local tag="$3"

while IFS= read -r asset_name; do
  [[ "$asset_name" == "$pkg-$version.$tag.bottle."*.tar.gz || "$asset_name" == "$pkg--$version.$tag.bottle."*.tar.gz ]] && return 0
done < "$RELEASED_ASSETS_FILE"

return 1
}

released_bottle_asset() {
local pkg="$1"
local version="$2"
local tag="$3"

while IFS= read -r asset_name; do
  if [[ "$asset_name" == "$pkg-$version.$tag.bottle."*.tar.gz ||
    "$asset_name" == "$pkg--$version.$tag.bottle."*.tar.gz ]]; then
    echo "$asset_name"
    return 0
  fi
done < "$RELEASED_ASSETS_FILE"

return 1
}

released_formula_checksum_matches() {
local pkg="$1"
local version="$2"
local formula_file="$REPO_ROOT/Formula/${pkg}.rb"
local asset_name
local release_digest
local formula_digest

[ -f "$formula_file" ] || return 0
asset_name=$(released_bottle_asset "$pkg" "$version" "ventura") || return 0
release_digest=$(awk -F '\t' -v asset="$asset_name" '
  $1 == asset { sub(/^sha256:/, "", $2); print $2; exit }
' "$RELEASED_ASSET_DIGESTS_FILE")
formula_digest=$(awk '$1 == "sha256" { gsub(/"/, "", $2); print $2; exit }' \
  "$formula_file")

if [ -z "$release_digest" ] || [ -z "$formula_digest" ]; then
  echo "  → Checksum metadata unavailable; skipping release checksum validation"
  return 0
fi

if [ "$release_digest" != "$formula_digest" ]; then
  echo "  → Formula checksum differs from published asset; will rebuild"
  echo "    Formula: $formula_digest"
  echo "    Release: $release_digest"
  return 1
fi

return 0
}

tap_formula_version_installed() {
local pkg="$1"
local version="$2"
local receipt="$(brew --cellar)/$pkg/$version/INSTALL_RECEIPT.json"

[ -f "$receipt" ] || return 1
jq -e '.source.tap == "quyleanh/tap"' "$receipt" >/dev/null 2>&1
}

package_needed_by_later_formula() {
local dependency="$1"
local consumer
local formula_file
local dependency_seen=false

for consumer in "${ORDERED[@]}"; do
  if [ "$dependency_seen" = true ]; then
    formula_file="$REPO_ROOT/Formula/${consumer}.rb"
    if [ -f "$formula_file" ] &&
      grep -Fq "depends_on \"quyleanh/tap/$dependency\"" "$formula_file"; then
      return 0
    fi
  fi
  [ "$consumer" = "$dependency" ] && dependency_seen=true
done

return 1
}

ensure_pkgconf_opt_aliases() {
local pkgconf_prefix
local opt_dir
local alias_name
local alias_path

pkgconf_prefix=$(brew --prefix quyleanh/tap/pkgconf)
opt_dir="$(brew --prefix)/opt"

for alias_name in pkg-config pkgconfig; do
  alias_path="$opt_dir/$alias_name"
  if [ -e "$alias_path" ] && [ ! -L "$alias_path" ]; then
    echo "  ❌ Cannot create pkgconf alias over non-symlink: $alias_path"
    return 1
  fi
  ln -sfn "$pkgconf_prefix" "$alias_path"
done

echo "  ℹ️  Restored pkgconf opt aliases: pkg-config, pkgconfig"
}

# ──────────────────────────────────────────────────────────────

# Step 4: Determine if a package needs rebuilding

# ──────────────────────────────────────────────────────────────

needs_build() {
local pkg="$1"
local formula_ref="$pkg"
[ "$pkg" = "ffmpeg" ] && formula_ref="quyleanh/tap/ffmpeg"
[ "$pkg" = "little-cms2" ] && formula_ref="homebrew/core/little-cms2"

if [ "$FORCE_BUILD" = "true" ]; then
echo "  → Force build enabled"
return 0
fi

  local info
  info=$(brew info --json=v1 "$formula_ref" 2>/dev/null)
  
  local latest
  latest=$(echo "$info" | jq -r '.[0].versions.stable // empty')

  local revision
  revision=$(echo "$info" | jq -r '.[0].revision // 0' || echo "0")
  if [ "${revision:-0}" -gt 0 ]; then
    latest="${latest}_${revision}"
  fi

if [ -z "$latest" ]; then
echo "  → Could not determine version, building to be safe"
return 0
fi

local released
released=$(get_released_version "$pkg")

echo "  → Latest  : $latest"
echo "  → Released: ${released:-<none>}"

if [ -z "$released" ]; then
echo "  → Not in release yet, will build"
return 0
fi

if [ "$latest" = "$released" ] && has_released_bottle "$pkg" "$latest"; then
  # A proper Ventura-tagged bottle is required for Homebrew to pour every
  # package during `brew upgrade` on the target macOS 13 machine.
  if ! has_released_bottle_tag "$pkg" "$latest" "ventura"; then
    echo "  → Missing Ventura bottle alias, will build"
    return 0
  fi
  if ! released_formula_checksum_matches "$pkg" "$latest"; then
    return 0
  fi
  echo "  → Up to date, skipping ✓"
  return 1
fi

if [ "$latest" = "$released" ]; then
echo "  → Matching version has no release bottle, will build"
return 0
fi

echo "  → New version available, will build"
return 0
}

# ──────────────────────────────────────────────────────────────
# Step 5: Immediate Package Publisher
# ──────────────────────────────────────────────────────────────

publish_package() {
  local pkg="$1"
  local pkg_version="$2"
  local bottle_file="$3"
  local json_file="${4:-}"

  # 1. Update the formula file locally
  if [ -n "$json_file" ] && [ -f "$json_file" ]; then
    echo "  📝 Generating Formula/${pkg}.rb..."
    BOTTLES_DIR="$OUTPUT_DIR" GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-}" \
      "$REPO_ROOT/scripts/update_formula.sh" "$json_file" || {
      echo "  ⚠️  Failed to generate formula for $pkg"
    }
  fi

  # 2. Upload to GitHub release immediately if GH_TOKEN & GITHUB_REPOSITORY are set
  local auth_token="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
  if [ -n "$GITHUB_REPOSITORY" ] && [ -n "$auth_token" ]; then
    export GH_TOKEN="$auth_token"

    # Delete older version assets of this package from the GitHub Release
    echo "  🔍 Checking for older release assets of $pkg to clean up..."
    local remote_assets
    remote_assets=$(gh release view stable --repo "$GITHUB_REPOSITORY" --json assets --jq '.assets[].name' 2>/dev/null || echo "")

    if [ -n "$remote_assets" ]; then
      while IFS= read -r old_asset; do
        [ -z "$old_asset" ] && continue
        if [[ "$old_asset" == "${pkg}-"* || "$old_asset" == "${pkg}--"* ]]; then
          local rest="${old_asset#"${pkg}-"}"
          rest="${rest#"-"}"
          if [[ "$rest" =~ ^([0-9]+|r[0-9]+)[0-9a-zA-Z_+.~-]*\.(ventura|sequoia|sonoma|monterey|big_sur|intel[0-9_]*)\.bottle ]] || [[ "$rest" =~ ^([0-9]+|r[0-9]+)[0-9a-zA-Z_+.~-]*\.bottle ]]; then
            if [ "$old_asset" != "$(basename "$bottle_file")" ] && [ "$old_asset" != "$(basename "$json_file")" ]; then
              echo "  🗑️  Deleting older release asset: $old_asset"
              gh release delete-asset stable "$old_asset" --repo "$GITHUB_REPOSITORY" -y 2>/dev/null || true
            fi
          fi
        fi
      done <<< "$remote_assets"
    fi

    echo "  🚀 Uploading $pkg bottle to GitHub Release (stable)..."

    local upload_files=("$bottle_file")
    if [ -n "$json_file" ] && [ -f "$json_file" ]; then
      upload_files+=("$json_file")
    fi

    if gh release upload stable "${upload_files[@]}" --repo "$GITHUB_REPOSITORY" --clobber; then
      echo "  ✅ Bottle uploaded to GitHub Release"
      echo "$pkg_version" > "$VERSIONS_CACHE_DIR/$pkg"
      echo "$(basename "$bottle_file")" >> "$RELEASED_ASSETS_FILE"
    else
      echo "  ⚠️  Failed to upload bottle to GitHub Release"
    fi

    # 3. Commit and push formula update immediately
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add "$REPO_ROOT/Formula" "$RESOLVED_FILE" "$BUILD_TIME_ESTIMATES_FILE"

    if ! git diff --staged --quiet; then
      echo "  💾 Committing & pushing formula update for $pkg..."
      git commit -m "chore(bottles): update $pkg ($pkg_version) [skip ci]

Built by GitHub Actions
Runner: macos-15-intel (Sequoia, Intel x86_64)" || true

      local push_success=false
      for attempt in 1 2 3; do
        if (git pull --rebase origin main 2>/dev/null || git pull --rebase 2>/dev/null) && (git push origin main 2>/dev/null || git push 2>/dev/null); then
          push_success=true
          echo "  ✅ Pushed commit for $pkg"
          break
        fi
        echo "  ⚠️  Push attempt $attempt failed, retrying in 3s..."
        sleep 3
      done
      if [ "$push_success" = false ]; then
        echo "  ⚠️  Could not push commit immediately. Will be pushed at workflow end."
      fi
    fi
  fi
}

get_build_time_estimate() {
  local pkg="$1"
  local estimate
  estimate=$(awk -v package="$pkg" '$1 == package { print $2; exit }' \
    "$BUILD_TIME_ESTIMATES_FILE" 2>/dev/null || true)
  if [[ ! "$estimate" =~ ^[0-9]+$ ]]; then
    estimate="$DEFAULT_BUILD_ESTIMATE_SECONDS"
  fi
  echo "$estimate"
}

record_build_time() {
  local pkg="$1"
  local observed_seconds="$2"
  local previous_seconds
  local recorded_seconds="$observed_seconds"
  local estimates_tmp

  previous_seconds=$(awk -v package="$pkg" '$1 == package { print $2; exit }' \
    "$BUILD_TIME_ESTIMATES_FILE" 2>/dev/null || true)
  if [[ "$previous_seconds" =~ ^[0-9]+$ ]] &&
    [ "$previous_seconds" -gt "$recorded_seconds" ]; then
    recorded_seconds="$previous_seconds"
  fi

  estimates_tmp=$(mktemp)
  awk -v package="$pkg" -v seconds="$recorded_seconds" '
    BEGIN { updated = 0 }
    $1 == package { print package "\t" seconds; updated = 1; next }
    { print }
    END { if (!updated) print package "\t" seconds }
  ' "$BUILD_TIME_ESTIMATES_FILE" > "$estimates_tmp"
  mv "$estimates_tmp" "$BUILD_TIME_ESTIMATES_FILE"
}

# ──────────────────────────────────────────────────────────────
# Step 6: Build loop
# ──────────────────────────────────────────────────────────────

echo "🔄 Updating Homebrew…"
brew update --quiet

if ! brew tap | grep -qx "homebrew/core"; then
  echo "📥 Tapping homebrew/core for brew bottle support…"
  brew tap --force homebrew/core 2>/dev/null || true
fi
echo ""

fetch_released_versions

BUILT=()
SKIPPED=()
FAILED=()
DEFERRED=()
START_TIME=$(date +%s)

for pkg in "${ORDERED[@]}"; do
CURRENT_TIME=$(date +%s)
ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

if [ "$ELAPSED_TIME" -gt "$MAX_BUILD_TIME" ]; then
  echo "──────────────────────────────────────"
  echo "⚠️ Time limit reached ($((MAX_BUILD_TIME / 60)) minutes elapsed). Stopping build loop gracefully."
  echo "This saves our progress so the CI can commit formulas and releases."
  echo "Run the workflow again to pick up where it left off!"
  echo "──────────────────────────────────────"
  break
fi

echo "──────────────────────────────────────"
echo "📦 $pkg (Elapsed: $((ELAPSED_TIME / 60))m / $((MAX_BUILD_TIME / 60))m)"
echo "──────────────────────────────────────"

formula_ref="$pkg"
[ "$pkg" = "ffmpeg" ] && formula_ref="quyleanh/tap/ffmpeg"
# This formula has a missing custom bottle. Build the maintained Homebrew Core
# source formula so the generated tap wrapper can restore it and its runtime
# dependency graph.
[ "$pkg" = "little-cms2" ] && formula_ref="homebrew/core/little-cms2"

if ! needs_build "$pkg"; then
SKIPPED+=("$pkg")
# Published leaves do not need to be installed on the ephemeral builder. Only
# restore a skipped formula when a later formula in ORDERED declares it.
if ! package_needed_by_later_formula "$pkg"; then
  echo "  ℹ️  No later package depends on $pkg; local restore not needed"
  echo ""
  continue
fi
# Ensure package is installed locally so dependents can link against it
released_version=$(get_released_version "$pkg")
if ! tap_formula_version_installed "$pkg" "$released_version"; then
  # The runner is macOS 15 while published tap bottles are deliberately tagged
  # for the macOS 13 target. Homebrew will not pour that older-tagged bottle on
  # the runner, so run the generated wrapper formula as a source install. Its
  # URL is the published archive and the wrapper unpacks it into the Cellar.
  released_formula_ref="$formula_ref"
  if [ -f "$REPO_ROOT/Formula/${pkg}.rb" ]; then
    released_formula_ref="quyleanh/tap/$pkg"
  fi
  echo "  ℹ️  Restoring published bottle for dependents..."
  # A GitHub runner may already have the same formula name from Homebrew Core.
  # Remove it before installing the tap-owned keg. ORDERED guarantees that each
  # declared dependency has already been restored and verified, so Homebrew's
  # supported dependency check will find it installed without recursive work.
  brew uninstall --force --ignore-dependencies "$pkg" 2>/dev/null || true
  # Intel GitHub runners may still have openssl@1.1 linked globally. Keep its
  # keg installed, but remove those links so openssl@3 can link cleanly.
  if [ "$pkg" = "openssl@3" ]; then
    brew unlink openssl@1.1 2>/dev/null || true
  fi
  restore_status=0
  brew install --build-from-source "$released_formula_ref" || restore_status=$?
  if ! tap_formula_version_installed "$pkg" "$released_version"; then
    echo "  ❌ Could not restore $released_formula_ref @ $released_version"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
  if [ "$restore_status" -ne 0 ]; then
    echo "  ℹ️  Bottle restored successfully despite a non-zero Homebrew link step"
  fi
else
  echo "  ℹ️  Tap bottle already installed locally ✓"
fi

if [ "$pkg" = "pkgconf" ] && ! ensure_pkgconf_opt_aliases; then
  FAILED+=("$pkg")
  echo ""
  continue
fi

echo ""
continue

fi

# Avoid starting a real source build that cannot finish with enough time left
# to bottle, upload and commit it. Estimates persist between workflow runs.
CURRENT_TIME=$(date +%s)
ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
REMAINING_TIME=$((MAX_BUILD_TIME - ELAPSED_TIME))
BUILD_ESTIMATE=$(get_build_time_estimate "$pkg")
PADDED_ESTIMATE=$(((BUILD_ESTIMATE * 125 + 99) / 100))
REQUIRED_TIME=$((PADDED_ESTIMATE + BUILD_TIME_RESERVE_SECONDS))

echo "  → Estimated build: $((BUILD_ESTIMATE / 60))m + 25% safety"
echo "  → Time remaining : $((REMAINING_TIME / 60))m (including publish reserve)"

if [ "$REQUIRED_TIME" -gt "$REMAINING_TIME" ]; then
  echo "  ⏸️  Deferring $pkg and the remaining dependency-ordered queue to the next run"
  DEFERRED+=("$pkg")
  break
fi

# Keep the generated bottle wrapper in place while deciding whether FFmpeg is
# current. Replace it with the maintained source formula only for a real build.
if [ "$pkg" = "ffmpeg" ]; then
  tap_formula_dir="$(brew --repository quyleanh/tap 2>/dev/null)/Formula"
  if [ -d "$tap_formula_dir" ]; then
    cp "$REPO_ROOT/scripts/ffmpeg.rb" "$tap_formula_dir/ffmpeg.rb"
  else
    echo "  ❌ Registered quyleanh/tap directory not found"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
fi

# Uninstall for a clean build

brew uninstall --ignore-dependencies "$pkg" 2>/dev/null || true

if [ "$pkg" = "ffmpeg" ]; then
  formula_revision=$(brew info --json=v2 quyleanh/tap/ffmpeg 2>/dev/null |
    jq -r '.formulae[0].revision // 0')
  echo "  → FFmpeg formula revision: ${formula_revision:-unknown}"
  if [ "${formula_revision:-0}" -lt 4 ]; then
    echo "  ❌ Homebrew is not seeing FFmpeg revision 4; refusing stale formula build"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
fi

# Formulae must be installed by tap-qualified name; Homebrew rejects arbitrary
# workspace paths that are not registered as taps.
BUILD_STARTED_AT=$(date +%s)
if brew install --build-bottle --overwrite "$formula_ref"; then
BUILD_FINISHED_AT=$(date +%s)
BUILD_DURATION=$((BUILD_FINISHED_AT - BUILD_STARTED_AT))
record_build_time "$pkg" "$BUILD_DURATION"
echo "  → Recorded build time: $((BUILD_DURATION / 60))m"
echo "  ✅ Installed, packing bottle…"

# Resolve actual Cellar path — may include revision suffix (_1, _2...)
cellar_path=$(ls -dt "$(brew --cellar)/$pkg/"*/ 2>/dev/null | head -1 | sed 's|/$||')
pkg_version=$(basename "$cellar_path")

if [ -z "$pkg_version" ] || [ ! -d "$cellar_path" ]; then
  echo "  ⚠️  Cellar path not found for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

# FFmpeg must remain usable on the user's macOS 13 Intel machine. Homebrew's
# macOS 15 linker can still emit LC_BUILD_VERSION=15 even when the actual
# deployment flags are lowered, so validate the incompatible symbol instead of
# rejecting the metadata alone.
if [ "$pkg" = "ffmpeg" ]; then
  ffmpeg_bin="$cellar_path/bin/ffmpeg"
  min_os=$(otool -l "$ffmpeg_bin" 2>/dev/null |
    awk '/LC_BUILD_VERSION/{seen=1; next} seen && /minos/{print $2; exit}')
  echo "  → FFmpeg minimum macOS: ${min_os:-unknown}"
  if nm -u "$cellar_path"/lib/*.dylib 2>/dev/null |
    grep -q "AVCaptureDeviceTypeContinuityCamera"; then
    echo "  ❌ FFmpeg still references the macOS 15-only AVFoundation symbol"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
  if [ -e "$cellar_path/lib/libavdevice.dylib" ] ||
    otool -L "$ffmpeg_bin" 2>/dev/null | grep -q '/libavdevice'; then
    echo "  ❌ FFmpeg still contains libavdevice; refusing to publish"
    FAILED+=("$pkg")
    echo ""
    continue
  fi
  echo "  ✅ No macOS 15-only AVFoundation symbols detected"
fi

echo "  📦 Packing bottle via Homebrew..."

# Let brew bottle generate BOTH the JSON and the deterministic tar.gz archive
# This ensures the SHA256 checksums mathematically match in the future!
brew bottle \
  --json \
  --root-url "https://github.com/${GITHUB_REPOSITORY}/releases/download/stable" \
  "$pkg" 2>/dev/null || true

# Move BOTH the natively generated tar.gz bottle and the JSON file to OUTPUT_DIR
# We find exactly what Homebrew generated to avoid hardcoding the OS tag (sequoia/ventura/etc)
find . -maxdepth 1 -name "${pkg}--*.json" -exec mv {} "$OUTPUT_DIR/" \;
find . -maxdepth 1 -name "${pkg}--*.tar.gz" -exec mv {} "$OUTPUT_DIR/" \;

# Find the tarball we just moved to verify it exists
bottle_path=$(find "$OUTPUT_DIR" -maxdepth 1 -name "${pkg}--*${pkg_version}*.tar.gz" | head -n 1)

if [ -z "$bottle_path" ] || [ ! -f "$bottle_path" ]; then
  echo "  ⚠️  brew bottle failed to generate the archive for $pkg"
  FAILED+=("$pkg")
  echo ""
  continue
fi

# Publish strictly Ventura-tagged bottles for macOS 13+.
# Rename the runner's bottle archive and JSON metadata to the native Ventura naming format
# so only Ventura bottles are uploaded to the release.
ventura_bottle_path="$OUTPUT_DIR/${pkg}-${pkg_version}.ventura.bottle.1.tar.gz"
mv "$bottle_path" "$ventura_bottle_path"

json_path=$(find "$OUTPUT_DIR" -maxdepth 1 -name "${pkg}--*${pkg_version}*.json" | head -n 1)
if [ -n "$json_path" ] && [ -f "$json_path" ]; then
  ventura_json_path="$OUTPUT_DIR/${pkg}-${pkg_version}.ventura.bottle.json"
  mv "$json_path" "$ventura_json_path"
fi

echo "  ✅ Done: $pkg @ $pkg_version ($(du -h "$ventura_bottle_path" | cut -f1))"
BUILT+=("$pkg")

# Immediately publish bottle to GitHub Release and push formula update to git
publish_package "$pkg" "$pkg_version" "$ventura_bottle_path" "${ventura_json_path:-}"

# Package stays installed in Cellar — next packages link against it for free

else
echo "  ❌ Build failed: $pkg"
FAILED+=("$pkg")
fi

echo ""
done

rm -rf "$VERSIONS_CACHE_DIR" "$RELEASED_ASSETS_FILE" "$RELEASED_ASSET_DIGESTS_FILE"

# ──────────────────────────────────────────────────────────────

# Summary

# ──────────────────────────────────────────────────────────────

echo "══════════════════════════════════════"
echo "Build Summary"
echo "══════════════════════════════════════"
echo "✅ Built   (${#BUILT[@]}): ${BUILT[*]:-none}"
echo "⏭️  Skipped (${#SKIPPED[@]}): ${SKIPPED[*]:-none}"
echo "⏸️  Deferred (${#DEFERRED[@]}): ${DEFERRED[*]:-none}"
echo "❌ Failed  (${#FAILED[@]}): ${FAILED[*]:-none}"
echo ""

[ ${#BUILT[@]} -eq 0 ] && [ ${#FAILED[@]} -eq 0 ] &&   
echo "Nothing new to build — all packages are up to date."

ls -lh "$OUTPUT_DIR/"*.tar.gz 2>/dev/null || echo "No bottles in output dir."

echo "BUILT_COUNT=${#BUILT[@]}"   >> "${GITHUB_OUTPUT:-/dev/null}"
echo "FAILED_COUNT=${#FAILED[@]}" >> "${GITHUB_OUTPUT:-/dev/null}"

if [ ${#FAILED[@]} -gt 0 ]; then
echo ""
echo "⚠️  Some packages failed. Check logs above."
exit 1
fi
