#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BOTTLES_DIR="${BOTTLES_DIR:-$REPO_ROOT/bottles}"
FORMULA_DIR="$REPO_ROOT/Formula"
# Thay bằng Username/Repo thực tế của bạn
TAP_NAME="quyleanh/tap" 
RELEASE_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/stable"

mkdir -p "$FORMULA_DIR"

echo "=== Formula Updater (Dependency Hijacking Edition) ==="

JSON_FILES=("$BOTTLES_DIR"/*.bottle.json)
if [ ${#JSON_FILES[@]} -eq 0 ] || [ ! -f "${JSON_FILES[0]}" ]; then
  echo "No bottle JSON files found."
  exit 1
fi

for json_file in "${JSON_FILES[@]}"; do
  pkg_name=$(jq -r 'keys[0]' "$json_file")
  echo "Processing: $pkg_name"

  # 1. Lấy thông tin cơ bản
  version=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.pkg_version' "$json_file")
  sha256=$(jq -r --arg pkg "$pkg_name" '.[$pkg].bottle.tags | to_entries[0].value.sha256' "$json_file")
  homepage=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.homepage' "$json_file")
  desc=$(jq -r --arg pkg "$pkg_name" '.[$pkg].formula.desc' "$json_file")

  # 2. Xử lý Class Name (Python@3.14 -> PythonAT314, ada-url -> AdaUrl)
  class_name=$(ruby -e '
    name = ARGV[0].capitalize
    name.gsub!(/[-_.\s]([a-zA-Z0-9])/) { Regexp.last_match(1).upcase }
    name.tr!("+", "x")
    name.sub!(/(.)@(\d)/, "\\1AT\\2")
    puts name
  ' "$pkg_name")

  # 3. HIJACK DEPENDENCIES: Trỏ mọi dependency về Tap của bạn
  # Điều này cực kỳ quan trọng để máy khách không chạy sang Homebrew Core
  deps=$(jq -r --arg pkg "$pkg_name" --arg tap "$TAP_NAME" '
    .[$pkg].formula.dependencies // [] | 
    map("  depends_on \"" + $tap + "/" + . + "\"") | 
    join("\n")
  ' "$json_file")

  formula_file="$FORMULA_DIR/${pkg_name}.rb"

  actual_tar=$(find "$BOTTLES_DIR" -maxdepth 1 -name "${pkg_name}--*.tar.gz" -exec basename {} \; | head -n 1)

  if [[ "$version" == *"_"* ]]; then
    base_ver="${version%%_*}"
    rev="${version##*_}"
    version_ruby=$(printf 'version "%s"\n  revision %s' "$base_ver" "$rev")
  else
    version_ruby="version \"$version\""
  fi

  # 4. Tạo nội dung Formula
  cat > "$formula_file" << RUBY
# Auto-generated by update_formula.sh
class ${class_name} < Formula
  desc "$desc"
  homepage "$homepage"
  $version_ruby
  
  # Sử dụng dummy URL để tải thẳng file pre-built .tar.gz
  url "$RELEASE_URL/$actual_tar"
  sha256 "$sha256"

${deps}

  def install
    # Giải nén bottle và copy nội dung thẳng vào Cellar prefix
    prefix.install Dir["*"]
  end

  test do
    # Đơn giản hóa test để tránh lỗi môi trường trên GitHub Runner
    assert_true true
  end
end
RUBY

  echo "  ✅ Done: ${pkg_name}.rb"
done